#!/usr/bin/env python3
"""Build the comprehensive API dataset for API.NEPA-PRO.COM"""
import json

# Each entry: name, url, description, auth (No/apiKey/OAuth), https (Yes/No), cors (Yes/No/Unknown)
DATA = {
  "Animals": [
    ["AdoptAPet", "https://www.adoptapet.com/public/apis/pet_list.html", "Resource to help get pets adopted", "apiKey", "Yes", "Yes"],
    ["Axolotl", "https://theaxolotlapi.netlify.app/", "Collection of axolotl pictures and facts", "No", "Yes", "No"],
    ["Cat Facts", "https://alexwohlbruck.github.io/cat-facts/", "Daily cat facts", "No", "Yes", "No"],
    ["Cataas", "https://cataas.com/", "Cat as a service (cats pictures and gifs)", "No", "Yes", "No"],
    ["Cats (TheCatAPI)", "https://docs.thecatapi.com/", "Pictures of cats from Tumblr", "apiKey", "Yes", "No"],
    ["Dog Facts", "https://dukengn.github.io/Dog-facts-API/", "Random dog facts", "No", "Yes", "Yes"],
    ["Dog API", "https://dog.ceo/dog-api/", "Based on the Stanford Dogs Dataset", "No", "Yes", "Yes"],
    ["eBird", "https://documenter.getpostman.com/view/664302/S1ENwy59", "Retrieve recent or notable birding observations within a region", "apiKey", "Yes", "No"],
    ["FishWatch", "https://www.fishwatch.gov/developers", "Information and pictures about individual fish species", "No", "Yes", "Yes"],
    ["HTTP Cat", "https://http.cat/", "Cat for every HTTP Status", "No", "Yes", "Yes"],
    ["HTTP Dog", "https://http.dog/", "Dogs for every HTTP response status code", "No", "Yes", "Yes"],
    ["IUCN", "http://apiv3.iucnredlist.org/api/v3/docs", "IUCN Red List of Threatened Species", "apiKey", "No", "No"],
    ["MeowFacts", "https://github.com/wh-iterabb-it/meowfacts", "Get random cat facts", "No", "Yes", "No"],
    ["Movebank", "https://github.com/movebank/movebank-api-doc", "Movement and Migration data of animals", "No", "Yes", "Yes"],
    ["Petfinder", "https://www.petfinder.com/developers/", "Petfinder is dedicated to helping pets find homes", "apiKey", "Yes", "Yes"],
    ["PlaceBear", "https://placebear.com/", "Placeholder bear pictures", "No", "Yes", "Yes"],
    ["PlaceDog", "https://place.dog", "Placeholder Dog pictures", "No", "Yes", "Yes"],
    ["PlaceKitten", "https://placekitten.com/", "Placeholder Kitten pictures", "No", "Yes", "Yes"],
    ["RandomDog", "https://random.dog/woof.json", "Random pictures of dogs", "No", "Yes", "Yes"],
    ["RandomDuck", "https://random-d.uk/api", "Random pictures of ducks", "No", "Yes", "No"],
    ["RandomFox", "https://randomfox.ca/floof/", "Random pictures of foxes", "No", "Yes", "No"],
    ["RescueGroups", "https://userguide.rescuegroups.org/display/APIDG/API+Developers+Guide+Home", "Pet adoption", "No", "Yes", "Unknown"],
    ["Shibe.Online", "http://shibe.online/", "Random pictures of Shiba Inu, cats or birds", "No", "Yes", "Yes"],
    ["The Dog API", "https://thedogapi.com/", "A public service all about Dogs", "apiKey", "Yes", "No"],
    ["xeno-canto", "https://xeno-canto.org/explore/api", "Bird recordings", "No", "Yes", "Unknown"],
    ["Zoo Animals", "https://zoo-animal-api.herokuapp.com/", "Facts and pictures of zoo animals", "No", "Yes", "Yes"],
  ],
  "Anime": [
    ["AniAPI", "https://aniapi.com/docs/", "Anime discovery, streaming & syncing with trackers", "OAuth", "Yes", "Yes"],
    ["AniDB", "https://wiki.anidb.net/HTTP_API_Definition", "Anime Database", "apiKey", "No", "Unknown"],
    ["AniList", "https://github.com/AniList/ApiV2-GraphQL-Docs", "Anime discovery & tracking", "OAuth", "Yes", "Unknown"],
    ["AnimeChan", "https://github.com/RocktimSaikia/anime-chan", "Anime quotes (over 10k+)", "No", "Yes", "No"],
    ["AnimeFacts", "https://chandan-02.github.io/anime-facts-rest-api/", "Anime Facts (over 100+)", "No", "Yes", "Yes"],
    ["AnimeNewsNetwork", "https://www.animenewsnetwork.com/encyclopedia/api.php", "Anime industry news", "No", "Yes", "Yes"],
    ["Catboy", "https://catboys.com/api", "Neko images, funny GIFs & more", "No", "Yes", "Yes"],
    ["Jikan", "https://jikan.moe", "Unofficial MyAnimeList API", "No", "Yes", "Yes"],
    ["Kitsu", "https://kitsu.docs.apiary.io/", "Anime discovery platform", "OAuth", "Yes", "Yes"],
    ["MangaDex", "https://api.mangadex.org/docs.html", "Manga Database and Community", "apiKey", "Yes", "Unknown"],
    ["MyAnimeList", "https://myanimelist.net/clubs.php?cid=13727", "Anime and Manga Database and Community", "OAuth", "Yes", "Unknown"],
    ["NekosBest", "https://docs.nekos.best", "Neko Images & Anime roleplaying GIFs", "No", "Yes", "Yes"],
    ["Shikimori", "https://shikimori.one/api/doc", "Anime discovery, tracking, forum, rates", "OAuth", "Yes", "Unknown"],
    ["Studio Ghibli", "https://ghibliapi.herokuapp.com", "Resources from Studio Ghibli films", "No", "Yes", "Yes"],
    ["Trace Moe", "https://soruly.github.io/trace.moe-api/", "Get the exact scene of an anime from a screenshot", "No", "Yes", "No"],
    ["Waifu.im", "https://waifu.im/docs", "Waifu pictures with multiple tags", "No", "Yes", "Yes"],
    ["Waifu.pics", "https://waifu.pics/docs", "Image sharing platform for anime images", "No", "Yes", "No"],
  ],
  "Anti-Malware": [
    ["AbuseIPDB", "https://docs.abuseipdb.com/", "IP/domain/URL reputation", "apiKey", "Yes", "Unknown"],
    ["AlienVault OTX", "https://otx.alienvault.com/api", "IP/domain/URL reputation", "apiKey", "Yes", "Unknown"],
    ["CAPEsandbox", "https://capev2.readthedocs.io/en/latest/usage/api.html", "Malware execution and analysis", "apiKey", "Yes", "Unknown"],
    ["Google Safe Browsing", "https://developers.google.com/safe-browsing/", "Google Link/Domain Flagging", "apiKey", "Yes", "Unknown"],
    ["MalShare", "https://malshare.com/doc.php", "Malware Archive / file sourcing", "apiKey", "Yes", "No"],
    ["MalwareBazaar", "https://bazaar.abuse.ch/api/", "Collect and share malware samples", "apiKey", "Yes", "Unknown"],
    ["NoPhishy", "https://rapidapi.com/Amiichu/api/exerra-phishing-check/", "Check links for known phishing attempts", "apiKey", "Yes", "Yes"],
    ["Phisherman", "https://phisherman.gg/", "IP/domain/URL reputation", "apiKey", "Yes", "Unknown"],
    ["Scanii", "https://docs.scanii.com/", "REST API to scan submitted documents/files for threats", "apiKey", "Yes", "Yes"],
    ["URLhaus", "https://urlhaus-api.abuse.ch/", "Bulk queries and Download Malware Samples", "No", "Yes", "Yes"],
    ["URLScan.io", "https://urlscan.io/about-api/", "Scan and Analyse URLs", "apiKey", "Yes", "Unknown"],
    ["VirusTotal", "https://www.virustotal.com/en/documentation/public-api/", "VirusTotal File/URL Analysis", "apiKey", "Yes", "Unknown"],
    ["Web of Trust", "https://support.mywot.com/hc/en-us/sections/360004477734-API-", "IP/domain/URL reputation", "apiKey", "Yes", "Unknown"],
  ],
  "Art & Design": [
    ["Art Institute of Chicago", "https://api.artic.edu/docs/", "Art collection from Chicago", "No", "Yes", "Yes"],
    ["Colormind", "http://colormind.io/api-access/", "Color scheme generator", "No", "No", "Unknown"],
    ["ColourLovers", "http://www.colourlovers.com/api", "Get various patterns, palettes and images", "No", "No", "Unknown"],
    ["Cooper Hewitt", "https://collection.cooperhewitt.org/api", "Smithsonian Design Museum", "apiKey", "Yes", "Unknown"],
    ["Dribbble", "https://developer.dribbble.com", "Discover the world's top designers & creatives", "OAuth", "Yes", "Unknown"],
    ["EmojiHub", "https://github.com/cheatsnake/emojihub", "Get emojis by categories and groups", "No", "Yes", "Yes"],
    ["Europeana", "https://pro.europeana.eu/resources/apis/search", "European Museum and Galleries content", "apiKey", "Yes", "Unknown"],
    ["Harvard Art Museums", "https://github.com/harvardartmuseums/api-docs", "Harvard art collection", "apiKey", "No", "Unknown"],
    ["Icon Horse", "https://icon.horse", "Favicons for any website, with fallbacks", "No", "Yes", "Yes"],
    ["Iconfinder", "https://developer.iconfinder.com", "Icons", "apiKey", "Yes", "Unknown"],
    ["Icons8", "https://img.icons8.com/", "Icons", "No", "Yes", "Unknown"],
    ["Lordicon", "https://lordicon.com/", "Icons with predone Animations", "No", "Yes", "Yes"],
    ["Metropolitan Museum of Art", "https://metmuseum.github.io/", "Met Museum of Art collection", "No", "Yes", "No"],
    ["Noun Project", "http://api.thenounproject.com/index.html", "Icons", "OAuth", "No", "Unknown"],
    ["PHP-Noise", "https://php-noise.com/", "Noise Background Image Generator", "No", "Yes", "Yes"],
    ["Pixel Encounter", "https://pixelencounter.com/api", "SVG Icon Generator", "No", "Yes", "No"],
    ["Rijksmuseum", "https://data.rijksmuseum.nl/object-metadata/api/", "RijksMuseum Data", "apiKey", "Yes", "Unknown"],
    ["xColors", "https://x-colors.herokuapp.com/", "Generate & convert colors", "No", "Yes", "Yes"],
  ],
  "Authentication & Authorization": [
    ["Auth0", "https://auth0.com", "Adaptable authentication and authorization platform", "apiKey", "Yes", "Yes"],
    ["GetOTP", "https://otp.dev/en/docs/", "Implement OTP flow quickly", "apiKey", "Yes", "No"],
    ["Micro User Service", "https://m3o.com/user", "User management and authentication", "apiKey", "Yes", "No"],
    ["MojoAuth", "https://mojoauth.com", "Secure and modern passwordless authentication", "apiKey", "Yes", "Yes"],
    ["SAWO Labs", "https://sawolabs.com", "Passwordless authentication", "apiKey", "Yes", "Yes"],
    ["Stytch", "https://stytch.com/", "User infrastructure for modern applications", "apiKey", "Yes", "No"],
    ["Warrant", "https://warrant.dev/", "APIs for authorization and access control", "apiKey", "Yes", "Yes"],
  ],
  "Blockchain": [
    ["Bitquery", "https://graphql.bitquery.io/ide", "Onchain GraphQL APIs & DEX APIs", "apiKey", "Yes", "Yes"],
    ["Chainlink", "https://chain.link/developer-resources", "Build hybrid smart contracts", "No", "Yes", "Unknown"],
    ["Chainpoint", "https://tierion.com/chainpoint/", "Anchor data to the Bitcoin blockchain", "No", "Yes", "Unknown"],
    ["Covalent", "https://www.covalenthq.com/docs/api/", "Multi-blockchain data aggregator platform", "apiKey", "Yes", "Unknown"],
    ["Etherscan", "https://etherscan.io/apis", "Ethereum explorer API", "apiKey", "Yes", "Yes"],
    ["Helium", "https://docs.helium.com/api/blockchain/introduction/", "Global distributed network for wireless coverage", "No", "Yes", "Unknown"],
    ["Nownodes", "https://nownodes.io/", "Blockchain-as-a-service via API", "apiKey", "Yes", "Unknown"],
    ["Steem", "https://developers.steem.io/", "Blockchain-based blogging and social media", "No", "No", "No"],
    ["The Graph", "https://thegraph.com", "Indexing protocol for querying networks like Ethereum", "apiKey", "Yes", "Unknown"],
    ["Watchdata", "https://docs.watchdata.io", "Simple and reliable Ethereum blockchain API", "apiKey", "Yes", "Unknown"],
  ],
  "Books": [
    ["Bhagavad Gita", "https://docs.bhagavadgitaapi.in", "Bhagavad Gita with 21+ author translations", "apiKey", "Yes", "Yes"],
    ["Bible-api", "https://bible-api.com/", "Free Bible API with multiple languages", "No", "Yes", "Yes"],
    ["British National Bibliography", "http://bnb.data.bl.uk/", "Books from British National Library", "No", "No", "Unknown"],
    ["Crossref Metadata", "https://github.com/CrossRef/rest-api-doc", "Books & Articles Metadata", "No", "Yes", "Unknown"],
    ["Google Books", "https://developers.google.com/books/", "Books data and search", "OAuth", "Yes", "Unknown"],
    ["Gutendex", "https://gutendex.com/", "Web-API for Project Gutenberg Books Library", "No", "Yes", "Unknown"],
    ["Open Library", "https://openlibrary.org/developers/api", "Books, book covers and related data", "No", "Yes", "No"],
    ["Penguin Publishing", "http://www.penguinrandomhouse.biz/webservices/rest/", "Books, book covers and related data", "No", "Yes", "Yes"],
    ["PoetryDB", "https://github.com/thundercomb/poetrydb", "Vast poetry collection", "No", "Yes", "Yes"],
    ["Quran Cloud", "https://alquran.cloud/api", "Retrieve any Ayah, Surah, Juz or the entire Quran", "No", "Yes", "Yes"],
    ["The Bible API", "https://docs.api.bible", "Everything you need from the Bible", "apiKey", "Yes", "Unknown"],
    ["Wizard World", "https://wizard-world-api.herokuapp.com/swagger/index.html", "Information from the Harry Potter universe", "No", "Yes", "Yes"],
  ],
  "Business": [
    ["Apache Superset", "https://superset.apache.org/docs/api", "Manage BI dashboards and data sources", "apiKey", "Yes", "Yes"],
    ["Charity Search", "http://charityapi.orghunter.com/", "Non-profit charity data", "apiKey", "No", "Unknown"],
    ["Clearbit Logo", "https://clearbit.com/docs#logo-api", "Search for company logos", "apiKey", "Yes", "Unknown"],
    ["Domainsdb.info", "https://domainsdb.info/", "Registered Domain Names Search", "No", "Yes", "No"],
    ["Freelancer", "https://developers.freelancer.com", "Hire freelancers to get work done", "OAuth", "Yes", "Unknown"],
    ["Gmail API", "https://developers.google.com/gmail/api/", "Flexible RESTful access to inbox", "OAuth", "Yes", "Unknown"],
    ["Google Analytics", "https://developers.google.com/analytics/", "Collect, configure and analyze your data", "OAuth", "Yes", "Unknown"],
    ["Mailchimp", "https://mailchimp.com/developer/", "Send marketing campaigns and transactional mails", "apiKey", "Yes", "Unknown"],
    ["mailjet", "https://www.mailjet.com/", "Marketing email and templates via API", "apiKey", "Yes", "Unknown"],
    ["Square", "https://developer.squareup.com/reference/square", "Take payments, manage refunds, customer checkout", "OAuth", "Yes", "Unknown"],
    ["Tomba email finder", "https://tomba.io/api", "Email Finder for B2B sales and email marketing", "apiKey", "Yes", "Yes"],
    ["Trello", "https://developers.trello.com/", "Boards, lists and cards to organize projects", "OAuth", "Yes", "Unknown"],
  ],
  "Calendar": [
    ["Calendarific", "https://calendarific.com/", "Worldwide Holidays", "apiKey", "Yes", "Unknown"],
    ["Festivo Public Holidays", "https://docs.getfestivo.com/docs/products/public-holidays-api/intro", "Advanced public holiday and observance service", "apiKey", "Yes", "Yes"],
    ["Google Calendar", "https://developers.google.com/google-apps/calendar/", "Display, create and modify Google calendar events", "OAuth", "Yes", "Unknown"],
    ["Hebrew Calendar", "https://www.hebcal.com/home/developer-apis", "Convert between Gregorian and Hebrew", "No", "No", "Unknown"],
    ["Holidays API", "https://holidayapi.com/", "Historical data regarding holidays", "apiKey", "Yes", "Unknown"],
    ["Nager.Date", "https://date.nager.at", "Public holidays for more than 90 countries", "No", "Yes", "No"],
    ["Public Holidays", "https://www.abstractapi.com/holidays-api", "National, regional, and religious holidays", "apiKey", "Yes", "Yes"],
    ["UK Bank Holidays", "https://www.gov.uk/bank-holidays.json", "Bank holidays in England, Scotland, Northern Ireland", "No", "Yes", "Unknown"],
  ],
  "Cloud Storage & File Sharing": [
    ["AnonFiles", "https://anonfiles.com/docs/api", "Upload and share your files anonymously", "No", "Yes", "Unknown"],
    ["Box", "https://developer.box.com/", "File Sharing and Storage", "OAuth", "Yes", "Unknown"],
    ["Dropbox", "https://www.dropbox.com/developers", "File Sharing and Storage", "OAuth", "Yes", "Unknown"],
    ["File.io", "https://www.file.io", "Super simple file sharing", "No", "Yes", "Unknown"],
    ["Filestack", "https://www.filestack.com", "File Uploader & File Upload API", "apiKey", "Yes", "Unknown"],
    ["GoFile", "https://gofile.io/api", "Unlimited size file uploads for free", "apiKey", "Yes", "Unknown"],
    ["Google Drive", "https://developers.google.com/drive/", "File Sharing and Storage", "OAuth", "Yes", "Unknown"],
    ["Gyazo", "https://gyazo.com/api/docs", "Save & Share screen captures instantly", "apiKey", "Yes", "Unknown"],
    ["Imgbb", "https://api.imgbb.com/", "Simple and quick private image sharing", "apiKey", "Yes", "Unknown"],
    ["OneDrive", "https://developer.microsoft.com/onedrive", "Microsoft File Sharing and Storage", "OAuth", "Yes", "Unknown"],
    ["Pantry", "https://getpantry.cloud/", "Free JSON storage for small projects", "No", "Yes", "Yes"],
    ["Pastebin", "https://pastebin.com/doc_api", "Plain Text Storage", "apiKey", "Yes", "Unknown"],
    ["Pinata", "https://docs.pinata.cloud/", "IPFS Pinning Services API", "apiKey", "Yes", "Unknown"],
    ["The Null Pointer", "https://0x0.st", "No-bullshit file hosting and URL shortening", "No", "Yes", "Unknown"],
    ["Web3 Storage", "https://web3.storage/", "Free file sharing with 1TB Space", "apiKey", "Yes", "Yes"],
  ],
  "Continuous Integration": [
    ["Bitrise", "https://api-docs.bitrise.io/", "Build tool and processes for development pipelines", "apiKey", "Yes", "Unknown"],
    ["Buddy", "https://buddy.works/docs/api/getting-started/overview", "Fastest CI/CD platform", "OAuth", "Yes", "Unknown"],
    ["CircleCI", "https://circleci.com/docs/api/v1-reference/", "Automate software development with CI/CD", "apiKey", "Yes", "Unknown"],
    ["Codeship", "https://docs.cloudbees.com/docs/cloudbees-codeship/latest/api-overview/", "Continuous Integration Platform in the cloud", "apiKey", "Yes", "Unknown"],
    ["Travis CI", "https://docs.travis-ci.com/api/", "Sync GitHub projects with Travis CI", "apiKey", "Yes", "Unknown"],
  ],
  "Cryptocurrency": [
    ["0x", "https://0x.org/api", "Token and pool stats across liquidity pools", "No", "Yes", "Yes"],
    ["1inch", "https://1inch.io/api/", "API for querying decentralize exchange", "No", "Yes", "Unknown"],
    ["Alchemy Ethereum", "https://docs.alchemy.com/alchemy/", "Ethereum Node-as-a-Service Provider", "apiKey", "Yes", "Yes"],
    ["Binance", "https://github.com/binance/binance-spot-api-docs", "Cryptocurrency Exchange", "apiKey", "Yes", "Unknown"],
    ["Bitfinex", "https://docs.bitfinex.com/docs", "Cryptocurrency Trading Platform", "apiKey", "Yes", "Unknown"],
    ["Bittrex", "https://bittrex.github.io/api/v3", "Next Generation Crypto Trading Platform", "apiKey", "Yes", "Unknown"],
    ["Blockchain.com", "https://www.blockchain.com/api", "Bitcoin Payment, Wallet & Transaction Data", "apiKey", "Yes", "Unknown"],
    ["CoinAPI", "https://docs.coinapi.io/", "All Currency Exchanges under a single api", "apiKey", "Yes", "No"],
    ["Coinbase", "https://developers.coinbase.com", "Bitcoin, Bitcoin Cash, Litecoin and Ethereum Prices", "apiKey", "Yes", "Unknown"],
    ["CoinCap", "https://docs.coincap.io/", "Real time Cryptocurrency prices", "No", "Yes", "Unknown"],
    ["CoinDesk", "https://old.coindesk.com/coindesk-api/", "Bitcoin Price Index in multiple currencies", "No", "Yes", "Unknown"],
    ["CoinGecko", "http://www.coingecko.com/api", "Cryptocurrency Price, Market, and Developer Data", "No", "Yes", "Yes"],
    ["Coinlore", "https://www.coinlore.com/cryptocurrency-data-api", "Cryptocurrencies prices, volume and more", "No", "Yes", "Unknown"],
    ["CoinMarketCap", "https://coinmarketcap.com/api/", "Cryptocurrencies Prices", "apiKey", "Yes", "Unknown"],
    ["Coinpaprika", "https://api.coinpaprika.com", "Cryptocurrencies prices, volume and more", "No", "Yes", "Yes"],
    ["CryptoCompare", "https://www.cryptocompare.com/api", "Cryptocurrencies Comparison", "No", "Yes", "Unknown"],
    ["Etherscan", "https://etherscan.io/apis", "Ethereum explorer API", "apiKey", "Yes", "Yes"],
    ["Gemini", "https://docs.gemini.com/rest-api/", "Cryptocurrencies Exchange", "No", "Yes", "Unknown"],
    ["Kraken", "https://docs.kraken.com/rest/", "Cryptocurrencies Exchange", "apiKey", "Yes", "Unknown"],
    ["KuCoin", "https://docs.kucoin.com/", "Cryptocurrency Trading Platform", "apiKey", "Yes", "Unknown"],
    ["Mempool", "https://mempool.space/api", "Bitcoin API Service for transaction fees", "No", "Yes", "No"],
    ["Messari", "https://messari.io/api", "API endpoints for thousands of crypto assets", "No", "Yes", "Unknown"],
    ["Nomics", "https://nomics.com/docs/", "Historical and realtime cryptocurrency prices", "apiKey", "Yes", "Yes"],
    ["Solana JSON RPC", "https://docs.solana.com/developing/clients/jsonrpc-api", "Interact with the Solana Blockchain", "No", "Yes", "Unknown"],
  ],
  "Currency Exchange": [
    ["1Forge", "https://1forge.com/forex-data-api/api-documentation", "Forex currency market data", "apiKey", "Yes", "Unknown"],
    ["Amdoren", "https://www.amdoren.com/currency-api/", "Free currency API with over 150 currencies", "apiKey", "Yes", "Unknown"],
    ["Bank of Russia", "https://www.cbr.ru/development/SXML/", "Exchange rates and currency conversion", "No", "Yes", "Unknown"],
    ["Currencylayer", "https://currencylayer.com", "Exchange rates and currency conversion", "apiKey", "Yes", "Unknown"],
    ["Currency-api", "https://github.com/fawazahmed0/currency-api", "Free Currency Exchange Rates with no rate limits", "No", "Yes", "Yes"],
    ["CurrencyFreaks", "https://currencyfreaks.com/", "Current and historical exchange rates (1K req/mo free)", "apiKey", "Yes", "Yes"],
    ["ExchangeRate-API", "https://www.exchangerate-api.com", "Free currency conversion", "apiKey", "Yes", "Yes"],
    ["Exchangerate.host", "https://exchangerate.host", "Free foreign exchange & crypto rates", "No", "Yes", "Unknown"],
    ["Fixer", "https://fixer.io", "Exchange rates and currency conversion", "apiKey", "No", "Unknown"],
    ["Frankfurter", "https://www.frankfurter.app/docs", "Exchange rates, currency conversion and time series", "No", "Yes", "Yes"],
    ["National Bank of Poland", "http://api.nbp.pl/en.html", "Currency exchange rates (XML and JSON)", "No", "Yes", "Yes"],
    ["VATComply.com", "https://www.vatcomply.com/documentation", "Exchange rates, geolocation, VAT validation", "No", "Yes", "Yes"],
  ],
  "Data Validation": [
    ["Lob.com", "https://lob.com/", "US Address Verification", "apiKey", "Yes", "Unknown"],
    ["Postman Echo", "https://www.postman-echo.com", "Test api server to receive and return values", "No", "Yes", "Unknown"],
    ["PurgoMalum", "http://www.purgomalum.com", "Content validator against profanity & obscenity", "No", "No", "Unknown"],
    ["US Autocomplete", "https://www.smarty.com/docs/cloud/us-autocomplete-pro-api", "Real-time address suggestions", "apiKey", "Yes", "Yes"],
    ["US Street Address", "https://www.smarty.com/docs/cloud/us-street-api", "Validate and append data for any US postal address", "apiKey", "Yes", "Yes"],
    ["VATlayer", "https://vatlayer.com/", "VAT number validation", "apiKey", "Yes", "Unknown"],
  ],
  "Development": [
    ["24 Pull Requests", "https://24pullrequests.com/api", "Promote open source collaboration during December", "No", "Yes", "Yes"],
    ["Agify.io", "https://agify.io", "Estimates the age from a first name", "No", "Yes", "Yes"],
    ["APIs.guru", "https://apis.guru/api-doc/", "Wikipedia for Web APIs, OpenAPI/Swagger specs", "No", "Yes", "Unknown"],
    ["Bitbucket", "https://developer.atlassian.com/bitbucket/api/2/reference/", "Bitbucket API", "OAuth", "Yes", "Unknown"],
    ["Bored API", "https://www.boredapi.com/", "Find random activities to fight boredom", "No", "Yes", "Unknown"],
    ["CDNJS", "https://api.cdnjs.com/libraries/jquery", "Library info on CDNJS", "No", "Yes", "Unknown"],
    ["Cloudflare Trace", "https://github.com/fawazahmed0/cloudflare-trace-api", "Get IP, timestamp, user agent, country code & more", "No", "Yes", "Yes"],
    ["CountAPI", "https://countapi.xyz", "Free counting service for tracking events", "No", "Yes", "Yes"],
    ["Docker Hub", "https://docs.docker.com/docker-hub/api/latest/", "Interact with Docker Hub", "apiKey", "Yes", "Yes"],
    ["Genderize.io", "https://genderize.io", "Estimates a gender from a first name", "No", "Yes", "Yes"],
    ["GitHub", "https://docs.github.com/en/free-pro-team@latest/rest", "Make use of GitHub repositories programmatically", "OAuth", "Yes", "Yes"],
    ["GitLab", "https://docs.gitlab.com/ee/api/", "Automate GitLab interaction", "OAuth", "Yes", "Unknown"],
    ["Google Firebase", "https://firebase.google.com/docs", "Google's mobile application development platform", "apiKey", "Yes", "Yes"],
    ["Google Fonts", "https://developers.google.com/fonts/docs/developer_api", "Metadata for all families served by Google Fonts", "apiKey", "Yes", "Unknown"],
    ["Google Sheets", "https://developers.google.com/sheets/api/reference/rest", "Read, write, and format Google Sheets data", "OAuth", "Yes", "Unknown"],
    ["Heroku", "https://devcenter.heroku.com/articles/platform-api-reference/", "REST API to programmatically manage Heroku", "OAuth", "Yes", "Yes"],
    ["Httpbin", "https://httpbin.org/", "Simple HTTP Request & Response Service", "No", "Yes", "Yes"],
    ["Icanhazip", "https://major.io/icanhazip-com-faq/", "IP Address API", "No", "Yes", "Yes"],
    ["IFTTT", "https://platform.ifttt.com/docs/connect_api", "IFTTT Connect API", "No", "Yes", "Unknown"],
    ["IP2WHOIS", "https://www.ip2whois.com/", "WHOIS domain name lookup", "apiKey", "Yes", "Unknown"],
    ["IPify", "https://www.ipify.org/", "Simple IP Address API", "No", "Yes", "Unknown"],
    ["IPinfo", "https://ipinfo.io/developers", "Simple IP Address API", "No", "Yes", "Unknown"],
    ["jsDelivr", "https://github.com/jsdelivr/data.jsdelivr.com", "Package info and download stats on jsDelivr CDN", "No", "Yes", "Yes"],
    ["JSONbin.io", "https://jsonbin.io", "Free JSON storage service", "apiKey", "Yes", "Yes"],
    ["Kroki", "https://kroki.io", "Creates diagrams from textual descriptions", "No", "Yes", "Yes"],
    ["Nationalize.io", "https://nationalize.io", "Estimate the nationality of a first name", "No", "Yes", "Yes"],
    ["Netlify", "https://docs.netlify.com/api/get-started/", "Hosting service for the programmable web", "OAuth", "Yes", "Unknown"],
    ["npm Registry", "https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md", "Query Node.js library info", "No", "Yes", "Unknown"],
    ["QR code (goqr.me)", "http://goqr.me/api/", "Generate and decode QR code graphics", "No", "Yes", "Unknown"],
    ["QuickChart", "https://quickchart.io/", "Generate chart and graph images", "No", "Yes", "Yes"],
    ["StackExchange", "https://api.stackexchange.com/", "Q&A forum for developers", "OAuth", "Yes", "Unknown"],
    ["Statically", "https://statically.io/", "A free CDN for developers", "No", "Yes", "Yes"],
  ],
  "Dictionaries": [
    ["Collins Dictionary", "https://api.collinsdictionary.com/api/v1/documentation/html/", "Bilingual Dictionary and Thesaurus Data", "apiKey", "Yes", "Unknown"],
    ["Free Dictionary", "https://dictionaryapi.dev/", "Definitions, phonetics, pronounciations, examples", "No", "Yes", "Unknown"],
    ["Lingua Robot", "https://www.linguarobot.io", "Word definitions, pronunciations, synonyms", "apiKey", "Yes", "Yes"],
    ["Merriam-Webster", "https://dictionaryapi.com/", "Dictionary and Thesaurus Data", "apiKey", "Yes", "Unknown"],
    ["OwlBot", "https://owlbot.info/", "Definitions with example sentence and photo", "apiKey", "Yes", "Yes"],
    ["Oxford Dictionary", "https://developer.oxforddictionaries.com/", "Dictionary Data", "apiKey", "Yes", "No"],
    ["Synonyms API", "https://www.synonyms.com/synonyms_api.php", "Synonyms, thesaurus and antonyms", "apiKey", "Yes", "Unknown"],
    ["Wiktionary", "https://en.wiktionary.org/w/api.php", "Collaborative dictionary data", "No", "Yes", "Yes"],
    ["Wordnik", "https://developer.wordnik.com", "Dictionary Data", "apiKey", "Yes", "Unknown"],
    ["Words API", "https://www.wordsapi.com/docs/", "Definitions and synonyms for 150,000+ words", "apiKey", "Yes", "Unknown"],
  ],
  "Documents & Productivity": [
    ["Airtable", "https://airtable.com/api", "Integrate with Airtable", "apiKey", "Yes", "Unknown"],
    ["Asana", "https://developers.asana.com/docs", "Programmatic access to your asana system", "apiKey", "Yes", "Yes"],
    ["ClickUp", "https://clickup.com/api", "Cloud-based project management tool", "OAuth", "Yes", "Unknown"],
    ["Clockify", "https://clockify.me/developers-api", "Push/pull time tracking data", "apiKey", "Yes", "Unknown"],
    ["CloudConvert", "https://cloudconvert.com/api/v2", "Online file converter for many formats", "apiKey", "Yes", "Unknown"],
    ["Html2PDF", "https://html2pdf.app/", "HTML/URL to PDF conversion", "apiKey", "Yes", "Unknown"],
    ["iLovePDF", "https://developer.ilovepdf.com/", "Convert, merge, split PDFs (250/mo free)", "apiKey", "Yes", "Yes"],
    ["JIRA", "https://developer.atlassian.com/server/jira/platform/rest-apis/", "Issue tracking and agile project management", "OAuth", "Yes", "Unknown"],
    ["Monday", "https://api.developer.monday.com/docs", "Update data inside a monday.com account", "apiKey", "Yes", "Unknown"],
    ["Notion", "https://developers.notion.com/docs/getting-started", "Integrate with Notion", "OAuth", "Yes", "Unknown"],
    ["pdflayer", "https://pdflayer.com", "HTML/URL to PDF", "apiKey", "Yes", "Unknown"],
    ["Pocket", "https://getpocket.com/developer/", "Bookmarking service", "OAuth", "Yes", "Unknown"],
    ["Todoist", "https://developer.todoist.com", "Todo Lists API", "OAuth", "Yes", "Unknown"],
    ["WakaTime", "https://wakatime.com/developers", "Automated time tracking leaderboards for programmers", "No", "Yes", "Unknown"],
  ],
  "Email": [
    ["Disify", "https://www.disify.com/", "Validate and detect disposable email addresses", "No", "Yes", "Yes"],
    ["DropMail", "https://dropmail.me/api/", "GraphQL API for ephemeral e-mail inboxes", "No", "Yes", "Unknown"],
    ["Email Validation", "https://www.abstractapi.com/email-verification-validation-api", "Validate email addresses for deliverability", "apiKey", "Yes", "Yes"],
    ["EVA", "https://eva.pingutil.com/", "Validate email addresses", "No", "Yes", "Yes"],
    ["Guerrilla Mail", "https://www.guerrillamail.com/GuerrillaMailAPI.html", "Disposable temporary Email addresses", "No", "Yes", "Unknown"],
    ["ImprovMX", "https://improvmx.com/api", "Free email forwarding service", "apiKey", "Yes", "Unknown"],
    ["Kickbox", "https://open.kickbox.com/", "Email verification API", "No", "Yes", "Yes"],
    ["mail.gw", "https://docs.mail.gw", "10 Minute Mail", "No", "Yes", "Yes"],
    ["mail.tm", "https://docs.mail.tm", "Temporary Email Service", "No", "Yes", "Yes"],
    ["mailboxlayer", "https://mailboxlayer.com", "Email address validation", "apiKey", "Yes", "Unknown"],
    ["MailCheck.ai", "https://www.mailcheck.ai/", "Prevent users from signing up with temp emails", "No", "Yes", "Unknown"],
    ["Sendgrid", "https://docs.sendgrid.com/api-reference/", "Cloud-based SMTP provider", "apiKey", "Yes", "Unknown"],
    ["Sendinblue", "https://developers.sendinblue.com/docs", "Marketing/transactional email and SMS", "apiKey", "Yes", "Unknown"],
    ["Verifier", "https://verifier.meetchopra.com/docs", "Verifies that a given email is real", "apiKey", "Yes", "Yes"],
  ],
  "Entertainment": [
    ["chucknorris.io", "https://api.chucknorris.io", "Hand curated Chuck Norris jokes", "No", "Yes", "Unknown"],
    ["Corporate Buzz Words", "https://github.com/sameerkumar18/corporate-bs-generator-api", "REST API for Corporate Buzz Words", "No", "Yes", "Yes"],
    ["Excuser", "https://excuser.herokuapp.com/", "Get random excuses for various situations", "No", "Yes", "Unknown"],
    ["Imgflip", "https://imgflip.com/api", "Gets an array of popular memes", "No", "Yes", "Unknown"],
    ["Meme Maker", "https://mememaker.github.io/API/", "REST API to create your own meme", "No", "Yes", "Unknown"],
    ["Random Useless Facts", "https://uselessfacts.jsph.pl/", "Get useless, but true facts", "No", "Yes", "Unknown"],
    ["Techy", "https://techy-api.vercel.app/", "Tech-savvy sounding phrases", "No", "Yes", "Unknown"],
    ["Yo Momma Jokes", "https://github.com/beanboi7/yomomma-apiv2", "REST API for Yo Momma Jokes", "No", "Yes", "Unknown"],
  ],
  "Environment": [
    ["BreezoMeter Pollen", "https://docs.breezometer.com/api-documentation/pollen-api/v2/", "Daily Forecast pollen conditions data", "apiKey", "Yes", "Unknown"],
    ["Carbon Interface", "https://docs.carboninterface.com/", "Calculate carbon (CO2) emissions estimates", "apiKey", "Yes", "Yes"],
    ["Climatiq", "https://docs.climatiq.io", "Environmental footprint of emission activities", "apiKey", "Yes", "Yes"],
    ["IQAir", "https://www.iqair.com/air-pollution-data-api", "Air quality and weather data", "apiKey", "Yes", "Unknown"],
    ["Luchtmeetnet", "https://api-docs.luchtmeetnet.nl/", "Air quality components for The Netherlands", "No", "Yes", "Unknown"],
    ["National Grid ESO", "https://data.nationalgrideso.com/", "Open data from Great Britain's Electricity System Operator", "No", "Yes", "Unknown"],
    ["OpenAQ", "https://docs.openaq.org/", "Open air quality data", "apiKey", "Yes", "Unknown"],
    ["PVWatts", "https://developer.nrel.gov/docs/solar/pvwatts/v6/", "Energy production photovoltaic (PV) energy systems", "apiKey", "Yes", "Unknown"],
    ["UK Carbon Intensity", "https://carbon-intensity.github.io/api-definitions/", "Official Carbon Intensity API for Great Britain", "No", "Yes", "Unknown"],
    ["Website Carbon", "https://api.websitecarbon.com/", "Estimate the carbon footprint of web pages", "No", "Yes", "Unknown"],
  ],
  "Events": [
    ["Eventbrite", "https://www.eventbrite.com/platform/api/", "Find events", "OAuth", "Yes", "Unknown"],
    ["SeatGeek", "https://platform.seatgeek.com/", "Search events, venues and performers", "apiKey", "Yes", "Unknown"],
    ["Ticketmaster", "http://developer.ticketmaster.com/products-and-docs/apis/getting-started/", "Search events, attractions, or venues", "apiKey", "Yes", "Unknown"],
  ],
  "Finance": [
    ["Aletheia", "https://aletheiaapi.com/", "Insider trading data, earnings call analysis", "apiKey", "Yes", "Yes"],
    ["Alpaca", "https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/", "Realtime and historical US market data", "apiKey", "Yes", "Yes"],
    ["Alpha Vantage", "https://www.alphavantage.co/", "Realtime and historical stock data", "apiKey", "Yes", "Unknown"],
    ["Binlist", "https://binlist.net/", "Database of IIN/BIN information", "No", "Yes", "Unknown"],
    ["Econdb", "https://www.econdb.com/api/", "Global macroeconomic data", "No", "Yes", "Yes"],
    ["Fed Treasury", "https://fiscaldata.treasury.gov/api-documentation/", "U.S. Department of the Treasury Data", "No", "Yes", "Unknown"],
    ["Finage", "https://finage.co.uk", "Stock, currency, crypto, indices real-time data", "apiKey", "Yes", "Unknown"],
    ["Financial Modeling Prep", "https://site.financialmodelingprep.com/developer/docs", "Realtime and historical stock data", "apiKey", "Yes", "Unknown"],
    ["Finnhub", "https://finnhub.io/docs/api", "Stocks, Currencies, Crypto Real-Time + Websocket", "apiKey", "Yes", "Unknown"],
    ["FRED", "https://fred.stlouisfed.org/docs/api/fred/", "Economic data from the Federal Reserve Bank of St. Louis", "apiKey", "Yes", "Yes"],
    ["IEX Cloud", "https://iexcloud.io/docs/api/", "Realtime & Historical Stock and Market Data", "apiKey", "Yes", "Yes"],
    ["Intrinio", "https://intrinio.com/", "A wide selection of financial data feeds", "apiKey", "Yes", "Unknown"],
    ["Marketstack", "https://marketstack.com/", "Real-Time, Intraday & Historical Market Data", "apiKey", "Yes", "Unknown"],
    ["OpenFIGI", "https://www.openfigi.com/api", "Equity, index, futures, options symbology", "apiKey", "Yes", "Yes"],
    ["Plaid", "https://www.plaid.com/docs", "Connect with user's bank accounts", "apiKey", "Yes", "Unknown"],
    ["Polygon", "https://polygon.io/", "Historical stock market data", "apiKey", "Yes", "Unknown"],
    ["SEC EDGAR", "https://www.sec.gov/edgar/sec-api-documentation", "Annual reports of public US companies", "No", "Yes", "Yes"],
    ["Twelve Data", "https://twelvedata.com/", "Stock market data (real-time & historical)", "apiKey", "Yes", "Unknown"],
    ["WallstreetBets", "https://dashboard.nbshare.io/apps/reddit/api/", "WallstreetBets Stock Comments Sentiment Analysis", "No", "Yes", "Unknown"],
    ["Yahoo Finance", "https://www.yahoofinanceapi.com/", "Real time Yahoo Finance data", "apiKey", "Yes", "Yes"],
    ["YNAB", "https://api.youneedabudget.com/", "Budgeting & Planning", "OAuth", "Yes", "Yes"],
  ],
  "Food & Drink": [
    ["BaconMockup", "https://baconmockup.com/", "Resizable bacon placeholder images", "No", "Yes", "Yes"],
    ["Chomp", "https://chompthis.com/api/", "Data about various grocery products and foods", "apiKey", "Yes", "Unknown"],
    ["Edamam Nutrition", "https://developer.edamam.com/edamam-docs-nutrition-api", "Nutrition Analysis", "apiKey", "Yes", "Unknown"],
    ["Edamam Recipes", "https://developer.edamam.com/edamam-docs-recipe-api", "Recipe Search", "apiKey", "Yes", "Unknown"],
    ["Foodish", "https://github.com/surhud004/Foodish", "Random pictures of food dishes", "No", "Yes", "Yes"],
    ["Fruityvice", "https://www.fruityvice.com", "Data about all kinds of fruit", "No", "Yes", "Unknown"],
    ["Kroger", "https://developer.kroger.com/reference", "Supermarket Data", "apiKey", "Yes", "Unknown"],
    ["LCBO", "https://lcboapi.com/", "Alcohol data", "apiKey", "Yes", "Unknown"],
    ["Open Brewery DB", "https://www.openbrewerydb.org", "Breweries, Cideries and Craft Beer Bottle Shops", "No", "Yes", "Yes"],
    ["Open Food Facts", "https://world.openfoodfacts.org/data", "Food Products Database", "No", "Yes", "Unknown"],
    ["PunkAPI", "https://punkapi.com/", "Brewdog Beer Recipes", "No", "Yes", "Unknown"],
    ["Spoonacular", "https://spoonacular.com/food-api", "Recipes, Food Products, and Meal Planning", "apiKey", "Yes", "Unknown"],
    ["TheMealDB", "https://www.themealdb.com/api.php", "Open database of recipes from around the world", "apiKey", "Yes", "Yes"],
    ["TheCocktailDB", "https://www.thecocktaildb.com/api.php", "Open database of drinks and cocktails", "apiKey", "Yes", "Yes"],
  ],
  "Games & Comics": [
    ["AmiiboAPI", "https://amiiboapi.com/", "Nintendo Amiibo information", "No", "Yes", "Yes"],
    ["Battle.net", "https://develop.battle.net/", "Blizzard Entertainment", "OAuth", "Yes", "Unknown"],
    ["Brawl Stars", "https://developer.brawlstars.com", "Brawl Stars Game Information", "apiKey", "Yes", "Unknown"],
    ["Chess.com", "https://www.chess.com/news/view/published-data-api", "Chess.com read-only REST API", "No", "Yes", "Unknown"],
    ["Clash of Clans", "https://developer.clashofclans.com", "Clash of Clans Game Information", "apiKey", "Yes", "Unknown"],
    ["Clash Royale", "https://developer.clashroyale.com", "Clash Royale Game Information", "apiKey", "Yes", "Unknown"],
    ["Comic Vine", "https://comicvine.gamespot.com/api/documentation", "Comics", "No", "Yes", "Unknown"],
    ["Deck of Cards", "http://deckofcardsapi.com/", "Deck of Cards", "No", "No", "Unknown"],
    ["Destiny The Game", "https://github.com/Bungie-net/api", "Bungie Platform API", "apiKey", "Yes", "Unknown"],
    ["Dota 2", "https://docs.opendota.com/", "Dota 2 data provided by OpenDota", "No", "Yes", "Unknown"],
    ["Dungeons & Dragons", "http://www.dnd5eapi.co/", "Reference for 5th Edition Spells, Classes, Monsters", "No", "No", "No"],
    ["EVE Online", "https://esi.evetech.net/ui", "Third-Party Developer Documentation", "OAuth", "Yes", "Unknown"],
    ["Final Fantasy XIV", "https://xivapi.com/", "Game data for Final Fantasy XIV game", "No", "Yes", "Unknown"],
    ["Fortnite", "https://fortnite-api.com/", "Fortnite Stats, Cosmetics, Items, News & More", "apiKey", "Yes", "Yes"],
    ["FreeToGame", "https://www.freetogame.com/api-doc", "Free-To-Play Games Database", "No", "Yes", "Yes"],
    ["Genshin Impact", "https://genshin.dev", "Genshin Impact game data", "No", "Yes", "Yes"],
    ["Halo", "https://developer.haloapi.com/", "Halo 5 and Halo Wars 2 Information", "apiKey", "Yes", "Unknown"],
    ["Hearthstone", "https://rapidapi.com/omgvamp/api/hearthstone", "All the Hearthstone cards", "apiKey", "Yes", "Unknown"],
    ["IGDB.com", "https://api-docs.igdb.com/", "Video Game Database", "apiKey", "Yes", "Unknown"],
    ["JokeAPI", "https://jokeapi.dev", "Programming, Miscellaneous and Dark Jokes", "No", "Yes", "Yes"],
    ["Marvel", "http://developer.marvel.com", "Marvel Comics", "apiKey", "No", "Unknown"],
    ["Mojang", "https://wiki.vg/Mojang_API", "Mojang / Minecraft API", "No", "Yes", "Unknown"],
    ["Open Trivia", "https://opentdb.com/api_config.php", "Trivia questions", "No", "Yes", "Unknown"],
    ["PandaScore", "https://developers.pandascore.co", "E-sports games and tournaments", "apiKey", "Yes", "Unknown"],
    ["PlayerUnknown's Battlegrounds", "https://developer.playbattlegrounds.com/", "PUBG Stats API", "apiKey", "Yes", "Unknown"],
    ["Pokémon", "https://pokeapi.co", "Pokémon Information", "No", "Yes", "Yes"],
    ["Pokémon TCG", "https://pokemontcg.io", "Pokémon TCG Information", "apiKey", "Yes", "Yes"],
    ["RAWG Video Games", "https://rawg.io/apidocs", "Explore 350,000+ games", "apiKey", "Yes", "Yes"],
    ["Rick and Morty", "https://rickandmortyapi.com", "Hundreds of characters, images, locations and episodes", "No", "Yes", "Yes"],
    ["Riot Games", "https://developer.riotgames.com/", "Game data for League of Legends", "apiKey", "Yes", "Unknown"],
    ["Scryfall", "https://scryfall.com/docs/api", "Magic: The Gathering database", "No", "Yes", "Yes"],
    ["Steam", "https://developer.valvesoftware.com/wiki/Steam_Web_API", "Steam Client Interaction", "OAuth", "Yes", "Unknown"],
    ["SuperHeroes", "https://superheroapi.com", "All the Superheroes and Villains data", "apiKey", "Yes", "Unknown"],
    ["Star Wars", "https://swapi.dev/", "All the Star Wars data", "No", "Yes", "Yes"],
    ["TCGdex", "https://tcgdex.dev", "Multi languages Pokémon TCG Information", "No", "Yes", "Yes"],
    ["TETR.IO", "https://tetr.io/about/api/", "Player, league and replay data from TETR.IO", "No", "Yes", "Yes"],
    ["Wargaming.net", "https://developers.wargaming.net/", "Wargaming.net info and stats", "apiKey", "Yes", "Unknown"],
  ],
  "Geocoding": [
    ["adresse.data.gouv.fr", "https://adresse.data.gouv.fr", "Address database of France", "No", "Yes", "Unknown"],
    ["administrative-divisons-db", "https://github.com/kamikazechaser/administrative-divisions-db", "Most countries' administrative divisions database", "No", "Yes", "Unknown"],
    ["Battuta", "http://battuta.medunes.net", "Country, region and city information", "apiKey", "No", "Unknown"],
    ["Bing Maps", "https://www.microsoft.com/maps/", "Create/customize digital maps with Bing data", "apiKey", "Yes", "Unknown"],
    ["bigdatacloud", "https://www.bigdatacloud.com/ip-geolocation-apis", "Powerful Geolocation, Networking, Parsing & more", "apiKey", "Yes", "Unknown"],
    ["Country", "https://country.is/", "Get visitor's country from IP", "No", "Yes", "Yes"],
    ["FreeGeoIP", "https://freegeoip.app/", "Free geo ip information, no API key required", "No", "Yes", "Yes"],
    ["GeoApi", "https://api.gouv.fr/api/geoapi.html", "French geographical data", "No", "Yes", "Unknown"],
    ["GeoDataSource", "https://www.geodatasource.com/web-service", "Geocoding of city name by lat/long", "apiKey", "Yes", "Unknown"],
    ["Geokeo", "https://geokeo.com", "Forward and reverse geocoding", "apiKey", "Yes", "Yes"],
    ["GeoNames", "http://www.geonames.org/", "Place names and other geographical data", "No", "No", "Unknown"],
    ["Google Earth Engine", "https://developers.google.com/earth-engine/", "Cloud-based platform for planetary-scale environment analysis", "apiKey", "Yes", "Unknown"],
    ["Google Maps", "https://developers.google.com/maps/", "Create/customize digital maps", "apiKey", "Yes", "Unknown"],
    ["HelloSalut", "https://www.fourtonfish.com/hellosalut/api/", "Get hello translation following user language", "No", "Yes", "Unknown"],
    ["HERE Maps", "https://developer.here.com", "Maps Traffic, Public Transit, Geocoding", "apiKey", "Yes", "Unknown"],
    ["IP 2 Country", "https://ip2country.info", "Map an IP to a country", "No", "Yes", "Yes"],
    ["IP Address Details", "https://ipinfo.io/", "Find geolocation with details", "No", "Yes", "Yes"],
    ["IP Geolocation", "https://ipgeolocation.io/", "IP Geolocation API", "apiKey", "Yes", "Yes"],
    ["IP Geolocation (Abstract)", "https://www.abstractapi.com/ip-geolocation-api", "Detailed location for any IP", "apiKey", "Yes", "Yes"],
    ["IP Location", "https://ip-api.com/", "Find IP address location information", "No", "Yes", "Yes"],
    ["IP Sidekick", "https://ipsidekick.com", "Geolocation API with detailed information about IPs", "apiKey", "Yes", "Unknown"],
    ["IP Vigilante", "https://www.ipvigilante.com/", "Free IP Geolocation API", "No", "Yes", "Unknown"],
    ["ipapi", "https://ipapi.co/api/#introduction", "Geolocation, currency, timezone, ASN, language", "No", "Yes", "Yes"],
    ["ipstack", "https://ipstack.com/", "Locate and identify website visitors by IP", "apiKey", "Yes", "Unknown"],
    ["Mapbox", "https://www.mapbox.com/developers/", "Custom online maps", "apiKey", "Yes", "Unknown"],
    ["Mapquest", "https://developer.mapquest.com/", "Maps, Geocoding, Directions, Search", "apiKey", "Yes", "Unknown"],
    ["Nominatim", "https://nominatim.org/release-docs/develop/api/Overview/", "Provides OpenStreetMap geocoding services", "No", "Yes", "Unknown"],
    ["One Map, Singapore", "https://www.onemap.gov.sg/docs/", "Singapore Land Authority REST API", "OAuth", "Yes", "Unknown"],
    ["OpenCage", "https://opencagedata.com", "Forward and reverse geocoding using open data", "apiKey", "Yes", "Yes"],
    ["OpenStreetMap", "http://wiki.openstreetmap.org/wiki/API", "Navigation, geolocation and geographical data", "OAuth", "Yes", "Unknown"],
    ["positionstack", "https://positionstack.com/", "Forward and reverse address geocoding", "apiKey", "Yes", "Unknown"],
    ["REST Countries", "https://restcountries.com", "Get information about countries via a RESTful API", "No", "Yes", "Yes"],
    ["TomTom", "https://developer.tomtom.com/", "Maps, Routing, Geocoding, Traffic", "apiKey", "Yes", "Unknown"],
    ["Uebermaps", "https://uebermaps.com/api/v2", "Discover and share maps with friends", "apiKey", "Yes", "Unknown"],
    ["ZIP API", "https://service.zipapi.us/zipcode/", "ZIP-code based geolocation, demographics, real estate", "apiKey", "Yes", "Yes"],
    ["Zippopotam", "http://www.zippopotam.us", "Get information about a place", "No", "No", "Unknown"],
  ],
  "Government": [
    ["BCLaws", "http://www.bclaws.ca/civix/template/complete/api/index.html", "Access to the laws of British Columbia, Canada", "No", "No", "Unknown"],
    ["Brazilian Chamber of Deputies", "https://dadosabertos.camara.leg.br/swagger/api.html", "Open Data from the Brazilian Chamber", "No", "Yes", "Unknown"],
    ["BusinessUSA", "https://business.usa.gov/developer", "U.S. government data on business", "apiKey", "Yes", "Unknown"],
    ["Census.gov", "https://www.census.gov/data/developers/data-sets.html", "US Census Bureau public data", "No", "Yes", "Unknown"],
    ["City, Berlin", "https://daten.berlin.de/", "Berlin city administration open data", "No", "Yes", "Unknown"],
    ["City, Nantes", "https://data.nantesmetropole.fr/pages/home/", "Nantes Métropole open data", "apiKey", "Yes", "Unknown"],
    ["City, New York", "https://opendata.cityofnewyork.us/", "New York City data", "No", "Yes", "Unknown"],
    ["City, Toronto", "https://open.toronto.ca/", "Toronto City Open Data", "No", "Yes", "Unknown"],
    ["Code.gov", "https://code.gov", "Federal Government open source initiative", "apiKey", "Yes", "Unknown"],
    ["Colorado Information Marketplace", "https://data.colorado.gov/", "Colorado State Government open data", "No", "Yes", "Unknown"],
    ["Data USA", "https://datausa.io/about/api/", "US Public Data", "No", "Yes", "Unknown"],
    ["Data.gov", "https://api.data.gov/", "US Government Data", "apiKey", "Yes", "Unknown"],
    ["Department of Veterans Affairs", "https://developer.va.gov/", "VA APIs Platform", "apiKey", "Yes", "No"],
    ["Federal Register", "https://www.federalregister.gov/developers/documentation/api/v1", "The daily journal of the US Government", "No", "Yes", "Unknown"],
    ["FEC", "https://api.open.fec.gov/developers/", "US Federal Election Committee data", "apiKey", "Yes", "Unknown"],
    ["Open Government, Australia", "https://www.data.gov.au/", "Australian Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, Belgium", "https://data.gov.be/en", "Belgium Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, Canada", "http://open.canada.ca/en/access-open-data", "Canadian Government Open Data", "No", "No", "Unknown"],
    ["Open Government, France", "https://www.data.gouv.fr/", "French Government Open Data", "apiKey", "Yes", "Unknown"],
    ["Open Government, India", "https://data.gov.in/", "Indian Government Open Data", "apiKey", "Yes", "Unknown"],
    ["Open Government, Italy", "https://www.dati.gov.it/", "Italy Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, New Zealand", "https://www.data.govt.nz/", "New Zealand Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, Romania", "http://data.gov.ro/", "Romania Government Open Data", "No", "No", "Unknown"],
    ["Open Government, Spain", "https://datos.gob.es/", "Spain Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, Taiwan", "https://data.gov.tw/", "Taiwan Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, Thailand", "https://data.go.th/", "Thailand Government Open Data", "apiKey", "Yes", "Unknown"],
    ["Open Government, UK", "https://data.gov.uk/", "UK Government Open Data", "No", "Yes", "Unknown"],
    ["Open Government, USA", "https://www.data.gov/", "United States Government Open Data", "No", "Yes", "Unknown"],
    ["Represent by Open North", "https://represent.opennorth.ca/", "Find representatives in Canada", "No", "Yes", "Unknown"],
    ["USAspending.gov", "https://api.usaspending.gov/", "US federal spending data", "No", "Yes", "Unknown"],
  ],
  "Health": [
    ["Cataas", "https://cataas.com/", "Cat as a service (cats pictures and gifs)", "No", "Yes", "Yes"],
    ["Covid-19", "https://covid19api.com/", "Covid 19 spread, infection and recovery", "No", "Yes", "Yes"],
    ["Covid-19 India", "https://api.covid19india.org/", "Tracking of Covid 19 cases in India", "No", "Yes", "No"],
    ["Covid-19 JHU CSSE", "https://github.com/CSSEGISandData/COVID-19", "Data on Covid-19 with daily updates", "No", "Yes", "Yes"],
    ["Diabetes", "http://predictbgl.com/api/", "Logging and retrieving diabetes information", "No", "No", "Unknown"],
    ["FoodData Central", "https://fdc.nal.usda.gov/", "National Nutrient Database for Standard Reference", "apiKey", "Yes", "Unknown"],
    ["Healthcare.gov", "https://www.healthcare.gov/developers/", "Educational content about US health insurance", "No", "Yes", "Unknown"],
    ["Humanitarian Data Exchange", "https://data.humdata.org/", "Open platform for sharing humanitarian data", "No", "Yes", "Unknown"],
    ["LAPIS", "https://lapis.cov-spectrum.org/", "Genomic sequences and metadata for SARS-CoV-2", "No", "Yes", "Unknown"],
    ["Lexigram", "https://docs.lexigram.io/v1/welcome", "NLP that extracts mentions of clinical concepts", "apiKey", "Yes", "Unknown"],
    ["Makeup", "http://makeup-api.herokuapp.com/", "Makeup Information", "No", "No", "Unknown"],
    ["MyAPNEA", "https://www.myapnea.org/api", "Sleep Apnea Information", "OAuth", "Yes", "Unknown"],
    ["NPPES", "https://npiregistry.cms.hhs.gov/registry/help-api", "National Plan & Provider Enumeration System", "No", "Yes", "Unknown"],
    ["Nutritionix", "https://developer.nutritionix.com/", "Largest verified nutrition database", "apiKey", "Yes", "Unknown"],
    ["openFDA", "https://open.fda.gov", "Public FDA data about drugs, devices and foods", "No", "Yes", "Unknown"],
    ["Orion Health", "https://developer.orionhealth.io/", "Medical platform for storing healthcare records", "OAuth", "Yes", "Unknown"],
    ["Quarantine", "https://quarantine.country/coronavirus/api", "Coronavirus Tracker API", "No", "Yes", "Unknown"],
    ["USDA Nutrients", "https://fdc.nal.usda.gov/", "National Nutrient Database", "No", "Yes", "Unknown"],
  ],
  "Jobs": [
    ["Adzuna", "https://developer.adzuna.com/overview", "Job board aggregator", "apiKey", "Yes", "Unknown"],
    ["Arbeitnow", "https://documenter.getpostman.com/view/18545278/UVJbJdKh", "Job board for Europe / Remote", "No", "Yes", "Yes"],
    ["Findwork", "https://findwork.dev/developers/", "Job board API", "apiKey", "Yes", "Yes"],
    ["GraphQL Jobs", "https://graphql.jobs/docs/api/", "Jobs with GraphQL", "No", "Yes", "Yes"],
    ["Jobs2Careers", "https://api.jobs2careers.com/api/spec.pdf", "Job aggregator", "apiKey", "Yes", "Unknown"],
    ["Jooble", "https://jooble.org/api/about", "Job search engine", "apiKey", "Yes", "Unknown"],
    ["Open Skills", "https://github.com/workforce-data-initiative/skills-api/wiki/API-Overview", "Job titles, skills and related jobs data", "No", "No", "Unknown"],
    ["Remote Hub", "https://api.remotehub.com", "Jobs and remote companies", "No", "Yes", "Yes"],
    ["Remote OK", "https://remoteok.io/api", "Jobs with location independence", "No", "Yes", "Unknown"],
    ["Remotive", "https://github.com/remotive-com/remote-jobs-api", "Remote jobs api", "No", "Yes", "Unknown"],
    ["The Muse", "https://www.themuse.com/developers/api/v2", "Job board and company profiles", "apiKey", "Yes", "Unknown"],
    ["Upwork", "https://developers.upwork.com/", "Freelance job board and management system", "OAuth", "Yes", "Unknown"],
    ["USAJOBS", "https://developer.usajobs.gov/", "US government job board", "apiKey", "Yes", "Unknown"],
  ],
  "Machine Learning": [
    ["AI For Thai", "https://aiforthai.in.th/index.php", "Free Various Thai AI API", "apiKey", "Yes", "Unknown"],
    ["Clarifai", "https://docs.clarifai.com", "Computer Vision", "OAuth", "Yes", "Unknown"],
    ["Cloudmersive", "https://www.cloudmersive.com/image-recognition-and-processing-api", "Image captioning, face recognition, NSFW classification", "apiKey", "Yes", "Yes"],
    ["Deepcode", "https://www.deepcode.ai", "AI for code review", "No", "Yes", "Unknown"],
    ["Dialogflow", "https://dialogflow.com/", "Natural Language Processing", "apiKey", "Yes", "Unknown"],
    ["EXUDE-API", "https://github.com/Himasnhu-AT/exude-api", "Filtering out the basic and ineffective words", "No", "Yes", "No"],
    ["Hirak Sentiment", "https://rapidapi.com/hirak/api/text-sentiment-analyser/", "Detect sentiment, emotion, hate-speech in text", "apiKey", "Yes", "Unknown"],
    ["Hugging Face", "https://huggingface.co/docs/api-inference/index", "NLP for various tasks", "apiKey", "Yes", "Unknown"],
    ["Imagga", "https://imagga.com/", "Image Recognition Solutions", "apiKey", "Yes", "Yes"],
    ["Inferdo", "https://rapidapi.com/user/inferdo", "Computer Vision services", "apiKey", "Yes", "Unknown"],
    ["IPS Online", "https://en-ipsonline.com/", "Real-time prediction product", "apiKey", "Yes", "Unknown"],
    ["Keen IO", "https://keen.io/", "Data Analytics", "apiKey", "Yes", "Unknown"],
    ["Time Door", "https://timedoor.io", "Time series analysis API", "apiKey", "Yes", "Yes"],
    ["Unplugg", "https://unplu.gg/test_api.html", "Forecasting API for timeseries data", "apiKey", "Yes", "Unknown"],
    ["WolframAlpha", "https://products.wolframalpha.com/api/", "Computational knowledge engine", "apiKey", "Yes", "Unknown"],
  ],
  "Music": [
    ["AI Mastering", "https://aimastering.com/api_docs/", "Automated music mastering", "apiKey", "Yes", "Unknown"],
    ["Audiomack", "https://www.audiomack.com/data-api/docs", "Stream and discover music", "OAuth", "Yes", "Unknown"],
    ["Bandsintown", "https://app.swaggerhub.com/apis/Bandsintown/PublicAPI/3.0.0", "Music Events", "No", "Yes", "Unknown"],
    ["Deezer", "https://developers.deezer.com/", "Music", "OAuth", "Yes", "Unknown"],
    ["Discogs", "https://www.discogs.com/developers/", "Music", "OAuth", "Yes", "Unknown"],
    ["Genrenator", "https://binaryjazz.us/genrenator-api/", "Music genre generator", "No", "Yes", "Unknown"],
    ["iTunes Search", "https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/", "Software products", "No", "Yes", "Unknown"],
    ["Jamendo", "https://developer.jamendo.com/v3.0", "Music", "OAuth", "Yes", "Unknown"],
    ["JioSaavn", "https://github.com/cyberboysumanjay/JioSaavnAPI", "Bollywood Music Streaming and Podcasts", "No", "Yes", "Unknown"],
    ["KKBOX", "https://developer.kkbox.com", "Songs, playlists from KKBOX Music", "OAuth", "Yes", "Unknown"],
    ["Last.fm", "https://www.last.fm/api", "Music", "apiKey", "Yes", "Unknown"],
    ["LyricsOVH", "https://lyricsovh.docs.apiary.io/", "Simple API to retrieve the lyrics of a song", "No", "Yes", "Unknown"],
    ["Mixcloud", "https://www.mixcloud.com/developers/", "Music", "OAuth", "Yes", "Yes"],
    ["MusicBrainz", "https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2", "Music", "No", "Yes", "Unknown"],
    ["Musixmatch", "https://developer.musixmatch.com/", "Music", "apiKey", "Yes", "Unknown"],
    ["Songkick", "https://www.songkick.com/developer/", "Music Events", "OAuth", "Yes", "Unknown"],
    ["Songsterr", "https://www.songsterr.com/a/wa/api/", "Provides guitar, bass and drums tabs and chords", "No", "Yes", "Unknown"],
    ["SoundCloud", "https://developers.soundcloud.com/docs/api/guide", "Stream Millions of Tracks", "OAuth", "Yes", "Unknown"],
    ["Spotify", "https://developer.spotify.com/web-api/", "View Music Artists, Tracks and Podcasts", "OAuth", "Yes", "Unknown"],
    ["TheAudioDB", "https://www.theaudiodb.com/api_guide.php", "Music", "apiKey", "Yes", "Unknown"],
    ["Vagalume", "https://api.vagalume.com.br/docs/", "Crowdsourced lyrics and music knowledge", "apiKey", "Yes", "Unknown"],
  ],
  "News": [
    ["Associated Press", "https://developer.ap.org/", "Search for news and metadata", "apiKey", "Yes", "Unknown"],
    ["Chronicling America", "http://chroniclingamerica.loc.gov/about/api/", "Provides access to millions of pages of historic US newspapers", "No", "No", "Unknown"],
    ["Currents", "https://currentsapi.services/", "Latest news published in various news sources", "apiKey", "Yes", "Yes"],
    ["Feedbin", "https://github.com/feedbin/feedbin-api", "RSS reader", "OAuth", "Yes", "Unknown"],
    ["GNews", "https://gnews.io/", "Search for news from various sources", "apiKey", "Yes", "Yes"],
    ["Graphs for Coronavirus", "https://corona.dnsforfamily.com/api.txt", "Find graphs of corona infection rates", "No", "Yes", "Yes"],
    ["Hacker News", "https://github.com/HackerNews/API", "Social news for CS and entrepreneurship", "No", "Yes", "No"],
    ["Inshorts News", "https://github.com/cyberboysumanjay/Inshorts-News-API", "Short 60-word news on various topics", "No", "Yes", "Unknown"],
    ["MarketAux", "https://www.marketaux.com/", "Live stock-filterable news with sentiment", "apiKey", "Yes", "Yes"],
    ["MediaStack", "https://mediastack.com/", "Free, simple REST API for live news and blog articles", "apiKey", "Yes", "Unknown"],
    ["NewsAPI", "https://newsapi.org/", "Headlines currently published on a range of news sources", "apiKey", "Yes", "Yes"],
    ["NewsData", "https://newsdata.io/", "News data for over 80 countries in JSON format", "apiKey", "Yes", "Unknown"],
    ["New York Times", "https://developer.nytimes.com/", "NYT articles, books, movies and more", "apiKey", "Yes", "Unknown"],
    ["NPR One", "http://dev.npr.org/api/", "Personalized news listening experience from NPR", "OAuth", "Yes", "Unknown"],
    ["Spaceflight News", "https://api.spaceflightnewsapi.net/v3/documentation", "Spaceflight related news", "No", "Yes", "Yes"],
    ["The Guardian", "http://open-platform.theguardian.com/", "Articles, tags, and other content from The Guardian", "apiKey", "Yes", "Unknown"],
    ["The Old Reader", "https://github.com/theoldreader/api", "RSS reader", "apiKey", "Yes", "Unknown"],
  ],
  "Open Data": [
    ["18F", "http://18f.github.io/API-All-the-X/", "US Federal Government / 18F", "No", "No", "Unknown"],
    ["Archive.org", "https://archive.readme.io/docs", "The Internet Archive", "No", "Yes", "Unknown"],
    ["BotsArchive", "https://botsarchive.com/docs.html", "JSON formatted details about Telegram public bots", "No", "Yes", "Unknown"],
    ["Callook.info", "https://callook.info", "United States amateur radio callsign lookups", "No", "Yes", "Unknown"],
    ["CARTO", "https://carto.com/", "Location Information Prediction", "apiKey", "Yes", "Unknown"],
    ["CivicFeed", "https://developers.civicfeed.com/", "News articles and public datasets", "apiKey", "Yes", "Unknown"],
    ["Enigma Public", "http://docs.enigma.com/public/public_v20_api_about.html", "Broadest collection of public data", "apiKey", "Yes", "Yes"],
    ["French Address Search", "https://geo.api.gouv.fr/adresse", "Address search via French Government", "No", "Yes", "Unknown"],
    ["Hipolabs Universities", "https://github.com/Hipo/university-domains-list", "Universities by country", "No", "Yes", "Yes"],
    ["Microlink.io", "https://microlink.io", "Extract structured data from any website", "No", "Yes", "Yes"],
    ["Recreation Information Database", "https://ridb.recreation.gov/", "US recreational areas and parks data", "apiKey", "Yes", "Unknown"],
    ["Roman Catholic Dioceses", "https://github.com/marcoceppi/roman-catholic-dioceses-api", "List of Roman Catholic Dioceses in JSON", "No", "Yes", "Yes"],
    ["Scoop.it", "http://www.scoop.it/dev", "Content Curation Service", "apiKey", "No", "Unknown"],
    ["Teleport", "https://developers.teleport.org/", "Quality of Life Data", "No", "Yes", "Unknown"],
    ["Wikidata", "https://www.wikidata.org/w/api.php?action=help", "Collaboratively edited knowledge base", "OAuth", "Yes", "Unknown"],
    ["Wikipedia", "https://www.mediawiki.org/wiki/API:Main_page", "Mediawiki Encyclopedia", "No", "Yes", "Unknown"],
    ["Yelp", "https://www.yelp.com/developers/documentation/v3", "Find local business", "OAuth", "Yes", "Unknown"],
  ],
  "Open Source Projects": [
    ["Countly", "https://api.count.ly", "Countly Web SDK", "No", "Yes", "Unknown"],
    ["Creative Commons Catalog", "https://api.openverse.engineering/v1/", "Search engine for openly-licensed media", "OAuth", "Yes", "Unknown"],
    ["Drupal.org", "https://www.drupal.org/drupalorg/docs/api", "Drupal.org", "No", "Yes", "Unknown"],
    ["EU Tenders", "https://ted.europa.eu/", "Tenders Electronic Daily, EU public procurement", "No", "Yes", "Unknown"],
    ["Evil Insult Generator", "https://evilinsult.com/api", "Evil insults", "No", "Yes", "Yes"],
    ["GitHub Contribution Chart Generator", "https://github-contributions.vercel.app/", "Visualize your GitHub contributions", "No", "Yes", "Yes"],
    ["GitHub ReadMe Stats", "https://github.com/anuraghazra/github-readme-stats", "Dynamically generated stats for GitHub readmes", "No", "Yes", "Yes"],
    ["Libraries.io", "https://libraries.io/api", "Open source software libraries", "apiKey", "Yes", "Unknown"],
  ],
  "Patent": [
    ["EPO", "https://developers.epo.org/", "European patent search system api", "OAuth", "Yes", "Unknown"],
    ["TIPO", "https://tiponet.tipo.gov.tw/Gazette/OpenData/OpenDataAPI.aspx?lang=en", "Taiwan patent search system api", "apiKey", "Yes", "Unknown"],
    ["USPTO", "https://www.uspto.gov/learning-and-resources/open-data-and-mobility", "USA patent api services", "No", "Yes", "Unknown"],
  ],
  "Personality": [
    ["Advice Slip", "http://api.adviceslip.com/", "Generate random advice slips", "No", "Yes", "Unknown"],
    ["Dictum", "https://github.com/fisenkodv/dictum", "API to get access to a collection of the most inspiring expressions of mankind", "No", "Yes", "Unknown"],
    ["FavQs.com", "https://favqs.com/api", "Provides featured quotes, qotd, search, and more", "apiKey", "Yes", "Unknown"],
    ["FOAAS", "http://www.foaas.com/", "Fuck Off As A Service", "No", "No", "Unknown"],
    ["Forismatic", "http://forismatic.com/en/api/", "Inspirational Quotes", "No", "No", "Unknown"],
    ["icanhazdadjoke", "https://icanhazdadjoke.com/api", "The largest selection of dad jokes on the internet", "No", "Yes", "Unknown"],
    ["kanye.rest", "https://kanye.rest", "REST API for random Kanye West quotes", "No", "Yes", "Yes"],
    ["Medium", "https://github.com/Medium/medium-api-docs", "Community of readers and writers offering unique perspectives on ideas", "OAuth", "Yes", "Unknown"],
    ["Programming Quotes", "https://programming-quotes-api.herokuapp.com/", "Programming Quotes API for open source projects", "No", "Yes", "Unknown"],
    ["Quotable Quotes", "https://github.com/lukePeavey/quotable", "Quotable is a free, open source quotations API", "No", "Yes", "Unknown"],
    ["Quote Garden", "https://pprathameshmore.github.io/QuoteGarden/", "REST API for more than 5000 famous quotes", "No", "Yes", "Unknown"],
    ["quoteclear", "https://quoteclear.com/api/", "Aesthetic Quotes Restful API for over 1500 inspirational quotes", "No", "Yes", "Yes"],
    ["Stoicism Quote", "https://github.com/tlcheah2/stoic-quote-lambda-public-api", "Quotes about Stoicism", "No", "Yes", "Unknown"],
    ["They Said So Quotes", "https://theysaidso.com/api/", "Quotes API for inspiring quotes", "apiKey", "Yes", "Unknown"],
    ["Traitify", "https://app.traitify.com/developer", "Assess, collect and analyze Personality", "No", "Yes", "Unknown"],
    ["Vadivelu HTTP Codes", "https://vadivelu.anoram.com/", "On demand HTTP Codes with images", "No", "Yes", "Unknown"],
    ["Zen Quotes", "https://zenquotes.io/", "Large collection of Zen quotes for inspiration", "No", "Yes", "Yes"],
  ],
  "Phone": [
    ["Abstract Phone Validation", "https://www.abstractapi.com/phone-validation-api", "Validate phone numbers globally", "apiKey", "Yes", "Yes"],
    ["Cloudmersive Phone Validation", "https://www.cloudmersive.com/phone-verification-api", "Phone number validation", "apiKey", "Yes", "Yes"],
    ["Numverify", "https://numverify.com", "Phone number validation", "apiKey", "Yes", "Unknown"],
    ["Phone Specs", "https://github.com/azharimm/phone-specs-api", "Phone search and specifications", "No", "Yes", "Unknown"],
    ["Veriphone", "https://veriphone.io", "Phone number validation & carrier lookup", "apiKey", "Yes", "Yes"],
  ],
  "Photography": [
    ["APITemplate.io", "https://apitemplate.io", "Auto-generate images and PDFs", "apiKey", "Yes", "Yes"],
    ["Bruzu", "https://docs.bruzu.com", "Image generation with query string", "apiKey", "Yes", "Unknown"],
    ["Dynamic Dummy Image Generator", "https://dummyimage.com/", "Dynamically generated placeholder images", "No", "Yes", "Yes"],
    ["Flickr", "https://www.flickr.com/services/api/", "Flickr Services", "OAuth", "Yes", "Unknown"],
    ["Getty Images", "http://developers.gettyimages.com/en/", "Stock photo data, courtesy of Getty Images", "OAuth", "Yes", "Unknown"],
    ["Gph", "https://developers.giphy.com/", "Get all your gifs", "apiKey", "Yes", "Unknown"],
    ["Imgur", "https://apidocs.imgur.com/", "Images", "OAuth", "Yes", "Unknown"],
    ["Lorem Picsum", "https://picsum.photos/", "Images from Unsplash", "No", "Yes", "Yes"],
    ["ObjectCut", "https://objectcut.com/", "Image Background removal", "apiKey", "Yes", "Yes"],
    ["Pexels", "https://www.pexels.com/api/", "Free Stock Photos and Videos", "apiKey", "Yes", "Yes"],
    ["Pixabay", "https://pixabay.com/sk/service/about/api/", "Photography", "apiKey", "Yes", "Unknown"],
    ["PlaceKeanu", "https://placekeanu.com/", "Placeholder Keanu Reeves pictures", "No", "Yes", "No"],
    ["Readme typing SVG", "https://github.com/DenverCoder1/readme-typing-svg", "Customizable typing SVGs", "No", "Yes", "Yes"],
    ["ReadMe Quotes", "https://github.com/PiyushSuthar/github-readme-quotes", "Dynamic quotes for github readmes", "No", "Yes", "Yes"],
    ["Remove.bg", "https://www.remove.bg/api", "Image Background removal", "apiKey", "Yes", "Yes"],
    ["ScreenShotLayer", "https://screenshotlayer.com/", "URL 2 Image", "No", "Yes", "Unknown"],
    ["Shutterstock", "https://api-reference.shutterstock.com/", "Stock images, footage, and music", "OAuth", "Yes", "Unknown"],
    ["Unsplash", "https://unsplash.com/developers", "Photography", "OAuth", "Yes", "Unknown"],
    ["Wallhaven", "https://wallhaven.cc/help/api", "Wallpapers", "apiKey", "Yes", "Unknown"],
  ],
  "Programming": [
    ["Codeforces", "https://codeforces.com/apiHelp", "Get access to Codeforces data", "apiKey", "Yes", "Unknown"],
    ["Hackerearth", "https://www.hackerearth.com/docs/wiki/developers/v4/", "For compiling and running code in several languages", "apiKey", "Yes", "Unknown"],
    ["Judge0 CE", "https://ce.judge0.com/", "Compile and run source code", "No", "Yes", "Unknown"],
    ["Mintlify", "https://docs.mintlify.com/introduction", "Documentation API", "apiKey", "Yes", "Unknown"],
  ],
  "Science & Math": [
    ["arXiv", "https://arxiv.org/help/api/user-manual", "Curated research-sharing platform", "No", "Yes", "Unknown"],
    ["CORE", "https://core.ac.uk/services#api", "Access the world's Open Access research papers", "apiKey", "Yes", "Unknown"],
    ["GBIF", "https://www.gbif.org/developer/summary", "Global Biodiversity Information Facility", "No", "Yes", "Yes"],
    ["inspirehep.net", "https://inspirehep.net/info/hep/api?ln=en", "High Energy Physics info system", "No", "Yes", "Unknown"],
    ["iNaturalist", "https://api.inaturalist.org/v1/docs/", "Crowdsourced species identification", "OAuth", "Yes", "Unknown"],
    ["ITIS", "https://www.itis.gov/ws_description.html", "Integrated Taxonomic Information System", "No", "Yes", "Unknown"],
    ["Launch Library 2", "https://thespacedevs.com/llapi", "Spaceflight launches and events database", "No", "Yes", "Yes"],
    ["Materials Platform for Data Science", "https://mpds.io/developer/", "Curated materials data", "apiKey", "Yes", "Yes"],
    ["Minor Planet Center", "http://www.asterank.com/mpc", "Asterank.com Information", "No", "No", "Unknown"],
    ["NASA", "https://api.nasa.gov", "NASA data, including imagery", "No", "Yes", "Unknown"],
    ["Newton", "https://newton.vercel.app", "Symbolic and Arithmetic Math Calculator", "No", "Yes", "Yes"],
    ["Numbers API", "http://numbersapi.com", "Facts about numbers", "No", "No", "Unknown"],
    ["Ocean Facts", "https://oceanfacts.herokuapp.com/", "All facts about oceans", "No", "Yes", "Unknown"],
    ["Open Notify", "http://open-notify.org/Open-Notify-API/", "ISS astronauts, current location, etc", "No", "No", "Unknown"],
    ["Open Science Framework", "https://developer.osf.io", "Repository and archive for study designs, research materials", "No", "Yes", "Unknown"],
    ["Purple Air", "https://www2.purpleair.com/", "Real Time Air Quality Monitoring", "No", "Yes", "Unknown"],
    ["SHARE", "https://share.osf.io/api/v2/", "Free, open dataset of research events and outputs", "No", "Yes", "Unknown"],
    ["SpaceX", "https://github.com/r-spacex/SpaceX-API", "Company, vehicle, launchpad and launch data", "No", "Yes", "Unknown"],
    ["Sunrise and Sunset", "https://sunrise-sunset.org/api", "Sunset and sunrise times for a given latitude and longitude", "No", "Yes", "Unknown"],
    ["TimeZoneDB", "https://timezonedb.com/api", "Provides a simple time zone database", "apiKey", "Yes", "Unknown"],
    ["USGS Earthquake Hazards Program", "https://earthquake.usgs.gov/fdsnws/event/1/", "Earthquakes data real-time", "No", "Yes", "Unknown"],
    ["USGS Water Services", "https://waterservices.usgs.gov/", "Water quality and level info for rivers and lakes", "No", "Yes", "Unknown"],
    ["World Bank", "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589", "World Data", "No", "Yes", "Unknown"],
  ],
  "Security": [
    ["BinaryEdge", "https://docs.binaryedge.io/api-v2.html", "Provide access to BinaryEdge data, threat intelligence", "apiKey", "Yes", "Unknown"],
    ["BitWarden", "https://bitwarden.com/help/api/", "Best open-source password manager", "OAuth", "Yes", "Unknown"],
    ["Censys", "https://censys.io/api", "Search engine for Internet connected host and devices", "apiKey", "Yes", "Unknown"],
    ["CRXcavator", "https://crxcavator.io/apidocs", "Chrome extension risk scoring", "apiKey", "Yes", "Unknown"],
    ["GitGuardian", "https://api.gitguardian.com/doc", "Secret detection on git repositories", "apiKey", "Yes", "Unknown"],
    ["HaveIBeenPwned", "https://haveibeenpwned.com/API/v3", "Passwords which have previously been exposed", "apiKey", "Yes", "Unknown"],
    ["Intelligence X", "https://github.com/IntelligenceX/SDK/blob/master/Intelligence%20X%20API.pdf", "Perform OSINT", "apiKey", "Yes", "Unknown"],
    ["LoginRadius", "https://www.loginradius.com/docs/", "Managed User Authentication Service", "apiKey", "Yes", "Yes"],
    ["Microsoft Security Response Center (MSRC)", "https://msrc.microsoft.com/report/developer", "Programmatic interfaces to engage with the MSRC", "No", "Yes", "Unknown"],
    ["Mozilla http scanner", "https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md", "Mozilla observatory http scanner", "No", "Yes", "Unknown"],
    ["Mozilla tls scanner", "https://github.com/mozilla/tls-observatory#api-endpoints", "Mozilla observatory tls scanner", "No", "Yes", "Unknown"],
    ["National Vulnerability Database", "https://nvd.nist.gov/vuln/Data-Feeds/JSON-feed-changelog", "U.S. National Vulnerability Database", "No", "Yes", "Unknown"],
    ["Pulsedive", "https://pulsedive.com/api/", "Scan, search and collect threat intelligence", "apiKey", "Yes", "Unknown"],
    ["SecurityTrails", "https://securitytrails.com/corp/apidocs", "Domain and IP related information", "apiKey", "Yes", "Unknown"],
    ["Shodan", "https://developer.shodan.io/", "Search engine for Internet connected devices", "apiKey", "Yes", "Unknown"],
    ["UK Police", "https://data.police.uk/docs/", "UK Police data", "No", "Yes", "Unknown"],
  ],
  "Shopping": [
    ["Best Buy", "https://bestbuyapis.github.io/api-documentation/#overview", "Products, Buying Options, Categories, Recommendations, Stores and Commerce", "apiKey", "Yes", "Unknown"],
    ["Bratabase", "https://developers.bratabase.com/", "Database of different types of Bra Sizes", "OAuth", "Yes", "Unknown"],
    ["Digikala", "https://www.digikala.com/", "Iranian Marketplace", "OAuth", "Yes", "Unknown"],
    ["DummyJSON", "https://dummyjson.com", "Different types of dummy data to develop, test and prototype", "No", "Yes", "Yes"],
    ["eBay", "https://developer.ebay.com/", "Sell and Buy on eBay", "OAuth", "Yes", "Unknown"],
    ["Fake Store", "https://fakestoreapi.com/", "Fake store rest API for your e-commerce", "No", "Yes", "Yes"],
    ["Flipkart Marketplace", "https://seller.flipkart.com/api-docs/FMSAPI.html", "Indian Marketplace for Sellers", "OAuth", "Yes", "Unknown"],
    ["Lazada", "https://open.lazada.com/doc/doc.htm", "E-commerce marketplace in Southeast Asia", "apiKey", "Yes", "Unknown"],
    ["Mercadolibre", "https://developers.mercadolibre.com.ar/", "Latin America's largest e-commerce", "OAuth", "Yes", "Unknown"],
    ["WooCommerce", "https://woocommerce.github.io/woocommerce-rest-api-docs/", "E-commerce plugin for WordPress", "apiKey", "Yes", "Unknown"],
  ],
  "Social": [
    ["aspose.email cloud", "https://product.aspose.cloud/email/family", "Email, calendar manipulation, parse and verification", "apiKey", "Yes", "Unknown"],
    ["Buffer", "https://buffer.com/developers/api", "Access to Buffer for publishing and analytics", "OAuth", "Yes", "Unknown"],
    ["Cisco Spark", "https://developer.ciscospark.com", "Team Collaboration Software", "OAuth", "Yes", "Unknown"],
    ["Discord", "https://discord.com/developers/docs/intro", "Make bots for Discord, integrate Discord onto an external platform", "OAuth", "Yes", "Unknown"],
    ["Disqus", "https://disqus.com/api/docs/auth/", "Communicate with Disqus data", "OAuth", "Yes", "Unknown"],
    ["Facebook", "https://developers.facebook.com/", "Facebook Login, Share on FB, Social Plugins, Analytics and more", "OAuth", "Yes", "Unknown"],
    ["Foursquare", "https://developer.foursquare.com/", "Interact with Foursquare users and places (geolocation-based check-ins, photos, tips, events, etc)", "OAuth", "Yes", "Unknown"],
    ["FullContact", "https://docs.fullcontact.com/", "Get Social Media profiles and contact Information", "apiKey", "Yes", "Unknown"],
    ["HackerNews", "https://github.com/HackerNews/API", "Social news for CS and entrepreneurship", "No", "Yes", "No"],
    ["Instagram", "https://www.instagram.com/developer/", "Instagram Login, Share on Instagram, Social Plugins and more", "OAuth", "Yes", "Unknown"],
    ["LinkedIn", "https://developer.linkedin.com/docs/rest-api", "Apply for jobs, share and more", "OAuth", "Yes", "Unknown"],
    ["Medium", "https://github.com/Medium/medium-api-docs", "Community of readers and writers offering unique perspectives", "OAuth", "Yes", "Unknown"],
    ["Meetup.com", "https://www.meetup.com/api/guide", "Data about Meetups from Meetup.com", "apiKey", "Yes", "Unknown"],
    ["Microsoft Graph", "https://docs.microsoft.com/en-us/graph/", "Access to data and intelligence in Microsoft 365", "OAuth", "Yes", "Yes"],
    ["MySocialApp", "https://mysocialapp.io", "Seamless Social Networking features", "apiKey", "Yes", "Unknown"],
    ["Pinterest", "https://developers.pinterest.com/", "The world's catalog of ideas", "OAuth", "Yes", "Unknown"],
    ["Reddit", "https://www.reddit.com/dev/api", "Homepage of the internet", "OAuth", "Yes", "Unknown"],
    ["Saidit", "https://www.saidit.net/dev/api", "Open Source Reddit Clone", "OAuth", "Yes", "Unknown"],
    ["Slack", "https://api.slack.com/", "Team Instant Messaging", "OAuth", "Yes", "Unknown"],
    ["Telegram Bot", "https://core.telegram.org/bots/api", "Simplified HTTP version of the MTProto API for bots", "apiKey", "Yes", "Unknown"],
    ["Telegram MTProto", "https://core.telegram.org/api#getting-started", "Read and write Telegram data", "apiKey", "Yes", "Unknown"],
    ["TikTok", "https://developers.tiktok.com/doc/login-kit-web", "Fetches user info and user's video posts on TikTok platform", "OAuth", "Yes", "Unknown"],
    ["Tumblr", "https://www.tumblr.com/docs/en/api/v2", "Read and write Tumblr Data", "OAuth", "Yes", "Unknown"],
    ["Twitch", "https://dev.twitch.tv/docs", "Game Streaming API", "OAuth", "Yes", "Unknown"],
    ["Twitter (X)", "https://developer.twitter.com/en/docs", "Read and write Twitter data", "OAuth", "Yes", "No"],
    ["vk", "https://vk.com/dev/sites", "Read and write VK data", "OAuth", "Yes", "Unknown"],
  ],
  "Sports & Fitness": [
    ["balldontlie", "https://balldontlie.io", "NBA Stats and Information", "No", "Yes", "Yes"],
    ["BikeWise", "https://www.bikewise.org/documentation/api_v2", "Bikewise is a place to learn about and report bike crashes, hazards and thefts", "No", "Yes", "Unknown"],
    ["Canadian Football League (CFL)", "http://api.cfl.ca/", "Official JSON API providing real-time league, team and player statistics about the CFL", "apiKey", "Yes", "No"],
    ["City Bikes", "http://api.citybik.es/v2/", "City Bikes around the world", "No", "No", "Unknown"],
    ["Ergast F1", "http://ergast.com/mrd/", "F1 data from the beginning of the world championships in 1950", "No", "Yes", "Unknown"],
    ["Fitbit", "https://dev.fitbit.com/", "Fitbit Information", "OAuth", "Yes", "Unknown"],
    ["Football (Soccer) Videos", "https://www.scorebat.com/video-api/", "Embed codes for goals and highlights from Premier League, Bundesliga, Serie A and many more", "No", "Yes", "Yes"],
    ["Football Prediction", "https://boggio-analytics.com/fp-api/", "Predictions for upcoming football matches", "apiKey", "Yes", "Unknown"],
    ["JCDecaux Bike", "https://developer.jcdecaux.com/", "JCDecaux's self-service bicycles", "apiKey", "Yes", "Unknown"],
    ["MLB Records and Stats", "https://appac.github.io/mlb-data-api-docs/", "Current and historical MLB statistics", "No", "No", "Unknown"],
    ["NBA Stats", "https://any-api.com/nba_com/nba_com/docs/API_Description", "Current and historical NBA Statistics", "No", "Yes", "Unknown"],
    ["NHL Records and Stats", "https://gitlab.com/dword4/nhlapi", "NHL historical data and statistics", "No", "Yes", "Unknown"],
    ["Sport List & Data", "https://developers.decathlon.com", "Database of sports practiced in the world", "OAuth", "Yes", "Yes"],
    ["Sportmonks Cricket", "https://www.sportmonks.com/cricket-api", "Cricket Data API for international and domestic matches", "apiKey", "Yes", "Unknown"],
    ["Sportmonks Football", "https://www.sportmonks.com/football-api", "Football data API for 1500+ Leagues, livescores, odds and predictions", "apiKey", "Yes", "Unknown"],
    ["Strava", "https://strava.github.io/api/", "Connect with athletes, activities and more", "OAuth", "Yes", "Unknown"],
    ["SuredBits", "https://suredbits.com/api/", "Query sports data, including teams, players, games, scores and statistics", "No", "No", "No"],
    ["TheSportsDB", "https://www.thesportsdb.com/api.php", "Crowd-Sourced Sports Data and Artwork", "apiKey", "Yes", "Yes"],
    ["Wger", "https://wger.de/en/software/api", "Workout manager data as exercises, muscles or equipment", "apiKey", "Yes", "Unknown"],
  ],
  "Test Data": [
    ["Bacon Ipsum", "https://baconipsum.com/json-api/", "A Meatier Lorem Ipsum Generator", "No", "Yes", "Unknown"],
    ["Dicebear Avatars", "https://avatars.dicebear.com/", "Generate random pixel-art avatars", "No", "Yes", "Unknown"],
    ["FakeJSON", "https://fakejson.com", "Service to generate test and fake data", "apiKey", "Yes", "Yes"],
    ["FakerAPI", "https://fakerapi.it/en", "APIs collection to get fake data", "No", "Yes", "Yes"],
    ["GeneratorMix", "https://www.generatormix.com/", "Random generators for many different categories", "No", "Yes", "Yes"],
    ["JSONPlaceholder", "http://jsonplaceholder.typicode.com/", "Fake data for testing and prototyping", "No", "Yes", "Unknown"],
    ["Loripsum", "http://loripsum.net/", "Plain Lorem Ipsum generator", "No", "No", "Unknown"],
    ["Mockaroo", "https://www.mockaroo.com/docs", "Generate fake data to JSON, CSV, TXT, SQL and XML", "apiKey", "Yes", "Unknown"],
    ["QuickMocker", "https://quickmocker.com", "API mocking tool to generate contextual, fake or random data", "No", "Yes", "Yes"],
    ["Random Data", "https://random-data-api.com/documentation", "Random data generator", "No", "Yes", "Unknown"],
    ["RandomUser", "https://randomuser.me", "Generates random user data", "No", "Yes", "Unknown"],
    ["RoboHash", "https://robohash.org/", "Generate random robot/alien avatars", "No", "Yes", "Unknown"],
    ["This Person Does not Exist", "https://thispersondoesnotexist.com", "Generates real-life faces of people who do not exist", "No", "Yes", "Unknown"],
    ["UUID Generator", "https://www.uuidtools.com/docs", "Generate UUIDs", "No", "Yes", "No"],
    ["Yes No", "https://yesno.wtf/api", "Generate yes or no randomly", "No", "Yes", "Unknown"],
  ],
  "Text Analysis": [
    ["Aylien Text Analysis", "https://docs.aylien.com/textapi/#getting-started", "A collection of information retrieval and natural language APIs", "apiKey", "Yes", "Unknown"],
    ["Cloudmersive Natural Language", "https://www.cloudmersive.com/nlp-api", "Natural language processing and text analysis", "apiKey", "Yes", "Yes"],
    ["Detect Language", "https://detectlanguage.com/", "Detects text language", "apiKey", "Yes", "Unknown"],
    ["Google Cloud Natural", "https://cloud.google.com/natural-language/docs/", "Natural language understanding technology, including sentiment, entity and syntax analysis", "apiKey", "Yes", "Unknown"],
    ["LanguageTool", "https://languagetool.org/http-api/swagger-ui/", "Style and grammar checker for 25+ languages", "No", "Yes", "Yes"],
    ["Semantria", "https://semantria.readme.io/docs", "Text Analytics with sentiment analysis, categorization & named entity extraction", "OAuth", "Yes", "Unknown"],
    ["Sentiment Analysis API", "https://www.aiapi.ai", "Sentiment analysis, entity extraction, content scoring", "apiKey", "Yes", "Unknown"],
    ["Watson Natural Language Understanding", "https://cloud.ibm.com/apidocs/natural-language-understanding/natural-language-understanding", "Natural language processing for advanced text analysis", "OAuth", "Yes", "Unknown"],
  ],
  "Tracking": [
    ["Aftership", "https://www.aftership.com/docs/api/4", "Track, manage and predict shipments", "apiKey", "Yes", "Unknown"],
    ["Correios", "https://cws.correios.com.br/ajuda", "Brazilian Mail Service", "apiKey", "Yes", "Unknown"],
    ["EasyPost", "https://www.easypost.com/docs/api", "Shipping APIs for tracking, rates, and labels", "apiKey", "Yes", "Unknown"],
    ["PostalPinCode", "http://www.postalpincode.in/Api-Details", "Provides Pincode details for India", "No", "Yes", "Unknown"],
    ["Postmon", "http://postmon.com.br", "An API to query Brazilian ZIP codes (CEP) easily", "No", "No", "Unknown"],
    ["Sweden", "https://developer.postnord.com/api", "Provides information about parcels in transport", "apiKey", "No", "Unknown"],
    ["Tracking-Status", "https://tracking-status.com/api/v1/docs/", "Open delivery information for everyone", "No", "Yes", "Yes"],
    ["UPS", "https://www.ups.com/upsdeveloperkit", "Shipment and Address information", "apiKey", "Yes", "Unknown"],
    ["WhatPulse", "https://help.whatpulse.org/api/", "Small application that measures your keyboard/mouse usage", "No", "Yes", "Unknown"],
  ],
  "Transportation": [
    ["AccuLynx", "https://acculynx.dev/api-reference", "AccuLynx is a roofing tracking software", "apiKey", "Yes", "Unknown"],
    ["ADS-B Exchange", "https://www.adsbexchange.com/data/", "Access real-time and historical data of any and all airbone aircraft", "No", "Yes", "Unknown"],
    ["airportsapi", "https://airport-web.appspot.com/api/docs/", "Get name and website-URL for airports by ICAO code", "No", "Yes", "Unknown"],
    ["AIS Hub", "http://www.aishub.net/api", "Real-time data of any marine and inland vessel equipped with AIS tracking system", "apiKey", "No", "Unknown"],
    ["Amadeus for Developers", "https://developers.amadeus.com/self-service", "Travel Search - Limited usage", "OAuth", "Yes", "Unknown"],
    ["AviationAPI", "https://docs.aviationapi.com", "FAA Aeronautical Charts and Publications, Airport Information, and Weather", "No", "Yes", "Yes"],
    ["aviationstack", "https://aviationstack.com/", "Real-time Flight Status & Global Aviation Data", "apiKey", "Yes", "Unknown"],
    ["BANO", "https://bano.openstreetmap.fr/", "Best Address National Database from French Government and OpenStreetMap", "No", "Yes", "Unknown"],
    ["Bay Area Rapid Transit", "http://api.bart.gov", "Stations and predicted arrivals for BART", "apiKey", "No", "Unknown"],
    ["BlaBlaCar", "https://dev.blablacar.com", "Search car sharing trips", "apiKey", "Yes", "Unknown"],
    ["Boston MBTA Transit", "https://www.mbta.com/developers/v3-api", "Stations and predicted arrivals for MBTA", "apiKey", "No", "Unknown"],
    ["Community Transit", "https://github.com/transitland/transitland-datastore/blob/master/README.md#api-endpoints", "Transitland API", "No", "Yes", "Unknown"],
    ["GraphHopper", "https://graphhopper.com/api/1/docs/", "A-to-B routing with turn-by-turn instructions", "apiKey", "Yes", "Unknown"],
    ["Icelandic APIs", "http://docs.apis.is/", "Open APIs that deliver services in or regarding Iceland", "No", "Yes", "Unknown"],
    ["Indian Railways", "http://api.erail.in/", "Indian Railways Information", "apiKey", "No", "Unknown"],
    ["Izi", "http://api-docs.izi.travel/", "Audio guide for travellers", "apiKey", "Yes", "Unknown"],
    ["Metro Lisboa", "http://app.metrolisboa.pt/status/getLinhas.php", "Delays in subway lines", "No", "No", "No"],
    ["Navitia", "https://api.navitia.io/", "The open API for building cool stuff with transport data", "apiKey", "Yes", "Unknown"],
    ["NS", "https://www.ns.nl/reisinformatie/ns-api", "Dutch Railways", "apiKey", "Yes", "Unknown"],
    ["Open Charge Map", "https://openchargemap.org/site/develop/api", "Global public registry of electric vehicle charging locations", "No", "Yes", "Unknown"],
    ["Open Sky Network", "https://opensky-network.org/apidoc/index.html", "Free real-time ADS-B aviation data", "No", "Yes", "Unknown"],
    ["OpenFlights", "https://openflights.org/data.html", "Airline, airport and route data", "OAuth", "Yes", "Unknown"],
    ["REFUGE Restrooms", "https://www.refugerestrooms.org/api-docs/", "Provides safe restroom access for transgender, intersex and gender nonconforming individuals", "No", "Yes", "Unknown"],
    ["Schiphol Airport", "https://developer.schiphol.nl/", "Schiphol", "apiKey", "Yes", "Unknown"],
    ["TransitLand", "https://transit.land/documentation/datastore/api-endpoints.html", "Transit aggregation service worldwide", "No", "Yes", "Unknown"],
    ["Transport for Atlanta, US", "http://www.itsmarta.com/app-developer-resources.aspx", "Marta", "No", "No", "Unknown"],
    ["Transport for Belgium", "https://hello.irail.be/api/", "Belgian transport API", "No", "Yes", "Unknown"],
    ["Transport for Berlin, Germany", "https://github.com/derhuerst/vbb-rest/blob/3/docs/index.md", "Third-party VBB API", "No", "Yes", "Unknown"],
    ["Transport for Bordeaux, France", "https://opendata.bordeaux-metropole.fr/api/", "Bordeaux Métropole public transport API", "apiKey", "Yes", "Unknown"],
    ["Transport for Budapest, Hungary", "https://bkkfutar.docs.apiary.io", "Budapest public transport API", "No", "Yes", "Unknown"],
    ["Transport for Chicago, US", "http://www.transitchicago.com/developers/", "Chicago Transit Authority", "No", "No", "Unknown"],
    ["Transport for Czech Republic", "https://www.chaps.cz/eng/products/idos-internet", "Czech transport API", "apiKey", "Yes", "Unknown"],
    ["Transport for Denver, US", "http://www.rtd-denver.com/gtfs-developer-guide.shtml", "RTD", "No", "No", "Unknown"],
    ["Transport for Finland", "https://digitransit.fi/en/developers/", "Finnish transport API", "No", "Yes", "Unknown"],
    ["Transport for Germany", "http://data.deutschebahn.com/dataset/api-fahrplan", "Deutsche Bahn (DB) API", "apiKey", "Yes", "Unknown"],
    ["Transport for Honolulu, US", "http://hea.thebus.org/api_info.asp", "Honolulu Transportation Information", "apiKey", "No", "Unknown"],
    ["Transport for India", "https://data.gov.in/sector/transport", "India Public Transport API", "apiKey", "Yes", "Unknown"],
    ["Transport for London, England", "https://api.tfl.gov.uk", "TfL API", "No", "Yes", "Unknown"],
    ["Transport for Madrid, Spain", "https://apidocs.emtmadrid.es/", "Madrid Public Transport API", "apiKey", "Yes", "Unknown"],
    ["Transport for Manchester, England", "https://developer.tfgm.com/", "TfGM API", "apiKey", "Yes", "No"],
    ["Transport for Minneapolis, US", "http://svc.metrotransit.org/", "Minnesota Transportation Information", "No", "Yes", "Unknown"],
    ["Transport for New York City, US", "http://datamine.mta.info/", "MTA", "apiKey", "Yes", "Unknown"],
    ["Transport for Norway", "http://reisapi.ruter.no/help", "Norwegian transport API", "No", "Yes", "Unknown"],
    ["Transport for Ottawa, Canada", "http://www.octranspo.com/index.php/developers", "Ottawa Transportation Information", "apiKey", "Yes", "Unknown"],
    ["Transport for Paris, France", "https://api-ratp.pierre-grimaud.fr/v4/doc", "RATP SNCF Unofficial API", "No", "Yes", "Unknown"],
    ["Transport for Philadelphia, US", "http://www3.septa.org/hackathon/", "SEPTA APIs", "No", "No", "Unknown"],
    ["Transport for Sao Paulo, Brazil", "http://www.sptrans.com.br/desenvolvedores/api-do-olho-vivo-guia-de-referencia/documentacao-api/", "SP public transport API", "apiKey", "Yes", "Unknown"],
    ["Transport for Sweden", "https://www.trafiklab.se/api", "Sweden's traffic API", "OAuth", "Yes", "Unknown"],
    ["Transport for Switzerland", "https://transport.opendata.ch/docs.html", "Swiss public transport API", "No", "Yes", "Unknown"],
    ["Transport for The Netherlands", "http://www.ns.nl/reisinformatie/ns-api", "NS, only trains", "apiKey", "Yes", "Unknown"],
    ["Transport for Toronto, Canada", "https://myttc.ca/developers", "Toronto Transit Commission", "No", "Yes", "Unknown"],
    ["Transport for Vancouver, Canada", "https://developer.translink.ca/", "TransLink", "OAuth", "Yes", "Unknown"],
    ["Transport for Washington, US", "https://developer.wmata.com/", "Washington Metropolitan Area Transit Authority", "apiKey", "Yes", "Unknown"],
    ["Transport of Tampere, Finland", "https://wiki.itsfactory.fi/index.php/Journeys_API", "Tampere public transport API", "No", "Yes", "Unknown"],
    ["Travel Payouts", "https://support.travelpayouts.com/hc/en-us/categories/200358578-API", "Travel & Hotels API", "apiKey", "Yes", "Unknown"],
    ["Uber", "https://developer.uber.com/products", "Uber ride requests and price estimation", "OAuth", "Yes", "Yes"],
    ["WhereIsMyTransport", "https://developer.whereismytransport.com/", "Platform for public transport data in emerging cities", "OAuth", "Yes", "Unknown"],
  ],
  "URL Shorteners": [
    ["1pt", "https://1pt.co/addurl", "Shorten URLs into 1pt.co/xxxxx", "No", "Yes", "No"],
    ["Bitly", "http://dev.bitly.com/get_started.html", "URL shortener and link management", "OAuth", "Yes", "Unknown"],
    ["CleanURI", "https://cleanuri.com/docs", "URL shortener service", "No", "Yes", "Yes"],
    ["Clico", "https://cli.co/developer-tools", "Branded link management", "apiKey", "Yes", "Yes"],
    ["ClickMeter", "https://support.clickmeter.com/hc/en-us/categories/201474986", "Monitor, compare and optimize your marketing links", "apiKey", "Yes", "Unknown"],
    ["Cutt.ly", "https://cutt.ly/api-documentation/cuttly-links-api", "URL shortener with branded links and analytics", "apiKey", "Yes", "Unknown"],
    ["dub.sh", "https://dub.sh/api", "Free, open source URL shortener", "apiKey", "Yes", "Yes"],
    ["Free URL Shortener", "https://1pt.co/", "Free URL Shortener providing custom short links", "No", "Yes", "Yes"],
    ["GoTiny", "https://gotiny.cc/api", "Minimalistic URL shortener that just shortens URL", "No", "Yes", "Yes"],
    ["Kutt", "https://docs.kutt.it/", "Free Modern URL Shortener", "apiKey", "Yes", "Yes"],
    ["Owo", "https://owo.vc/api", "URL Shortener", "No", "Yes", "No"],
    ["Quirk", "https://quirk.gg/api", "Branded URL shortener", "apiKey", "Yes", "Unknown"],
    ["TinyURL", "https://tinyurl.com/app/dev", "Service for shortening URLs", "apiKey", "Yes", "Unknown"],
    ["Zapier URL Shortener", "https://zapier.com/apps/url-shortener/integrations", "URL Shortener by Zapier", "No", "Yes", "Unknown"],
  ],
  "Vehicle": [
    ["Brazilian Vehicles and Prices", "https://deividfortuna.github.io/fipe/", "Vehicles information from Fundação Instituto de Pesquisas Econômicas - Fipe", "No", "Yes", "Unknown"],
    ["Kelley Blue Book", "http://developer.kbb.com/#!/data/1-Default", "Vehicle info, pricing, configuration, plus much more", "apiKey", "Yes", "No"],
    ["Mercedes-Benz", "https://developer.mercedes-benz.com/apis", "Telematics data, remotely access vehicle functions", "apiKey", "Yes", "No"],
    ["NHTSA", "https://vpic.nhtsa.dot.gov/api/", "NHTSA Product Information Catalog and Vehicle Listing", "No", "Yes", "Unknown"],
    ["Smartcar", "https://smartcar.com/docs/", "Lock and unlock vehicles and get data like odometer reading, location, fuel tank level", "OAuth", "Yes", "No"],
  ],
  "Video": [
    ["Dailymotion", "https://developer.dailymotion.com/", "Dailymotion Developer API", "OAuth", "Yes", "Unknown"],
    ["MovieTongue", "https://api.movietongue.com/", "Provides JSON data for the most famous Tongue Twisters", "No", "Yes", "Unknown"],
    ["Open Movie Database", "http://www.omdbapi.com/", "Movie information", "apiKey", "Yes", "Unknown"],
    ["ScreenPI.com", "https://screenpi.com/api-documentation/", "Screen capture/recording APIs", "apiKey", "Yes", "Yes"],
    ["Streamable", "https://streamable.com/documentation", "Video Sharing platform", "apiKey", "Yes", "Unknown"],
    ["TMDb", "https://www.themoviedb.org/documentation/api", "Community-based movie data", "apiKey", "Yes", "Unknown"],
    ["Trakt", "https://trakt.tv/b/api-docs", "Movie and TV Data", "apiKey", "Yes", "Unknown"],
    ["TVDB", "https://thetvdb.com/wiki/index.php/Programmers_API", "Television data", "apiKey", "Yes", "Unknown"],
    ["TVMaze", "http://www.tvmaze.com/api", "TV Show Data", "No", "Yes", "Unknown"],
    ["Vimeo", "https://developer.vimeo.com/", "Vimeo Developer API", "OAuth", "Yes", "Unknown"],
    ["YouTube", "https://developers.google.com/youtube/", "Add YouTube functionality to your sites and apps", "OAuth", "Yes", "Unknown"],
  ],
  "Weather": [
    ["7Timer!", "http://www.7timer.info/doc.php?lang=en", "Weather, especially for Astroweather", "No", "No", "Unknown"],
    ["AccuWeather", "https://developer.accuweather.com/apis", "Weather and forecast data", "apiKey", "Yes", "Unknown"],
    ["aerisweather", "https://www.aerisweather.com/support/docs/api/", "Weather data and Forecasts", "apiKey", "Yes", "Yes"],
    ["APIXU", "https://www.apixu.com/doc/request.aspx", "Real-time weather and forecast", "apiKey", "Yes", "Unknown"],
    ["Foreca", "https://developer.foreca.com", "Weather", "OAuth", "Yes", "Unknown"],
    ["MetaWeather", "https://www.metaweather.com/api/", "Weather", "No", "Yes", "No"],
    ["Meteorologisk Institutt", "https://api.met.no/weatherapi/documentation", "Weather and climate data", "User-Agent", "Yes", "Unknown"],
    ["NOAA Climate Data", "https://www.ncdc.noaa.gov/cdo-web/", "Past climate data from numerous stations and sources", "apiKey", "Yes", "Unknown"],
    ["ODWeather", "http://api.oceandrivers.com/static/docs.html", "Weather and weather webcams", "No", "No", "Unknown"],
    ["OpenUV", "https://www.openuv.io", "Real-time UV Index Forecast", "apiKey", "Yes", "Unknown"],
    ["OpenWeatherMap", "https://openweathermap.org/api", "Weather", "apiKey", "Yes", "Unknown"],
    ["Storm Glass", "https://stormglass.io/", "Global marine weather from multiple sources", "apiKey", "Yes", "Yes"],
    ["Tomorrow", "https://docs.tomorrow.io", "Weather API Powered by Proprietary Technology", "apiKey", "Yes", "Unknown"],
    ["US Weather", "https://www.weather.gov/documentation/services-web-api", "US National Weather Service", "No", "Yes", "Yes"],
    ["Visual Crossing", "https://www.visualcrossing.com/weather-api", "Global historical and weather forecast data", "apiKey", "Yes", "Yes"],
    ["weather-api", "https://github.com/robertoduessmann/weather-api", "A RESTful free API to check the weather", "No", "Yes", "No"],
    ["WeatherAPI", "https://www.weatherapi.com/docs/", "Free Weather and Geolocation API", "apiKey", "Yes", "Yes"],
    ["Weatherbit", "https://www.weatherbit.io/api", "Weather", "apiKey", "Yes", "Unknown"],
    ["Weatherstack", "https://weatherstack.com/", "Real-Time & Historical World Weather Data API", "apiKey", "Yes", "Unknown"],
    ["World Weather Online", "https://www.worldweatheronline.com/developer/", "Weather and Marine API", "apiKey", "Yes", "Unknown"],
    ["Yandex.Weather", "https://yandex.com/dev/weather/", "Assesses weather condition in specific locations", "apiKey", "Yes", "Unknown"],
  ],
}

# Convert to a normalized list
out = {"categories": [], "total": 0}
for cat_name, apis in DATA.items():
  entries = []
  for row in apis:
    entries.append({
      "name": row[0],
      "url": row[1],
      "description": row[2],
      "auth": row[3],
      "https": row[4],
      "cors": row[5],
      "free": True,  # all entries are free-tier accessible
    })
  out["categories"].append({"name": cat_name, "slug": cat_name.lower().replace(" & ", "-and-").replace(" ", "-").replace("--", "-"), "apis": entries, "count": len(entries)})
  out["total"] += len(entries)

print(f"Total categories: {len(out['categories'])}")
print(f"Total APIs: {out['total']}")

with open("/home/claude/apinepa/apis.json", "w") as f:
  json.dump(out, f, indent=2, ensure_ascii=False)
print("Written /home/claude/apinepa/apis.json")
